### ISSUE TITLE
Broadcasting problem?

### ISSUE THREAD

**Issue by magic282** [dmlc/mxnet#2396] opened 2016-06-12 02:34 UTC
Hi all,

I am implementing the seq2seq model. I have already implemented a simple one with fixed input/output sequence length. I am trying to use both bucketing and masking since in some tasks like neural machine translation the length of sequence differs a lot.

For example in the LSTM encoder:

```python
# embeding layer
data = mx.sym.Variable('source')
# label = mx.sym.Variable('softmax_label')
embed = mx.sym.Embedding(data=data, input_dim=self.vocab_size + 1,
                         weight=embed_weight, output_dim=self.embed_dim, name='source_embed')
wordvec = mx.sym.SliceChannel(data=embed, num_outputs=self.seq_len, squeeze_axis=1)
if self.use_masking:
    input_mask = mx.sym.Variable('source_mask')
    masks = mx.sym.SliceChannel(data=input_mask, num_outputs=self.seq_len)

hidden_all = []
for seqidx in range(self.seq_len):
    hidden = wordvec[seqidx]
    if self.use_masking:
        mask = masks[seqidx]

    # stack LSTM
    for i in range(self.num_of_layer):
        if i == 0:
            dp_ratio = 0.
        else:
            dp_ratio = self.dropout
        next_state = lstm(self.state_dim, indata=hidden,
                          prev_state=last_states[i],
                          param=param_cells[i],
                          seqidx=seqidx, layeridx=i, dropout=dp_ratio)
        if self.use_masking:
            # hidden = mx.sym.broadcast_mul((1.0 - mask), hidden) + mx.sym.broadcast_mul(mask, next_state.h)
            hidden = mx.sym.broadcast_mul(mx.sym.broadcast_minus(1.0, mask), hidden) + mx.sym.broadcast_mul(mask, next_state.h)
            # hidden = (1.0 - mask) * hidden + mask * next_state.h
        else:
            hidden = next_state.h
        last_states[i] = next_state
    # decoder
    if self.dropout > 0.:
        hidden = mx.sym.Dropout(data=hidden, p=self.dropout)
    hidden_all.append(hidden)

return hidden_all
```

When I use `hidden = (1.0 - mask) * hidden + mask * next_state.h`
I got the error `mxnet.base.MXNetError: InferShape Error in _mul13's rhs argument` so I assume the operator is not correct here.

Then I changed it to `hidden = mx.sym.broadcast_mul(mx.sym.broadcast_minus(1.0, mask), hidden) + mx.sym.broadcast_mul(mask, next_state.h)`
I got the error `TypeError: Compose expect Symbol as arguments` so I noticed that the `broadcast_mul` needs two symbols.

After that I tried doing nothing by `hidden = mx.sym.broadcast_mul(mask, next_state.h)` in both encoder and decoder. This time I got another error: `mxnet.base.MXNetError: [10:30:48] D:\Projects\opensource\mxnet\src\symbol\static_graph.cc:488: Check failed: it != grad_map.end() bad graph: Cannot find node slicechannel1's 0-th output`

Any hints with these errors? 
Many thanks!

**Comment by sxjscience** [comment] 2016-06-12 06:24
Will changing the code to this `hidden = mx.sym.broadcast_mul(1.0 - mask, hidden) + mx.sym.broadcast_mul(mask, next_state.h)` help? Also the broadcasting OPs currently do not support some shape combinations, see https://github.com/dmlc/mxnet/blob/master/src/operator/elementwise_binary_broadcast_op-inl.h#L27-L38 .

**Comment by magic282** [comment] 2016-06-12 06:32
@sxjscience Nope. The error is `mxnet.base.MXNetError: InferShape Error in _plus2's rhs argument`

**Comment by magic282** [comment] 2016-06-12 06:36
The shape is:
```python
self.provide_data = [(source_data_name, (batch_size, self.default_bucket_key[0])),
                             (source_mask_name, (batch_size, self.default_bucket_key[0])),
                             (target_data_name, (batch_size, self.default_bucket_key[1])),
                             (target_mask_name, (batch_size, self.default_bucket_key[1]))] \
                            + source_init_states + target_init_states
self.provide_label = [(label_name, (self.batch_size, self.default_bucket_key[1]))]
```
where default_bucket_key[0] is seq length for source, [1] for target.

**Comment by sxjscience** [comment] 2016-06-12 06:38
@magic282 It seems that `hidden` and `next_state.h` have different shapes.

**Comment by magic282** [comment] 2016-07-04 10:48
Hi @sxjscience , I have fixed the above mentioned problems. 
However, when I run the code with GPU, it will stuck at:
```
Summary of dataset ==================
bucket of (1, 1) : 1550 samples
bucket of (6, 6) : 7556 samples
bucket of (11, 11) : 7477 samples
bucket of (16, 16) : 7308 samples
bucket of (21, 21) : 6109 samples
01:43:31 INFO:Start training with [gpu(0)]
```
I debugged and found that the code stuck at here model.py, line 245:
```python
# evaluate at end, so we can lazy copy
executor_manager.update_metric(eval_metric, data_batch.label)
```
It is very weird that if I use CPU, it runs properly. 
Also, If I run the s2s model without masking, it runs properly. 
I doubt that the problem is similar to issue https://github.com/dmlc/mxnet/issues/709 
So I reboot and test the GPU with mxnet rnn example. The problem remains.

After re-compile the dll with debug model, I got the follow error:
![capture](https://cloud.githubusercontent.com/assets/2285145/16558366/d1b13cc2-4217-11e6-85d3-eee3641fddb9.JPG)

Any hints for this?

Thank you.

**Comment by sxjscience** [comment] 2016-07-04 10:59
@magic282 Could you try if this PR fixes the problem? https://github.com/dmlc/mshadow/pull/146

**Comment by magic282** [comment] 2016-07-04 11:16
@sxjscience I tried the last windows [release](https://github.com/dmlc/mxnet/releases/tag/20160531), it works. The not working one is built from the latest source code. I will try your PR later.

**Comment by sxjscience** [comment] 2016-07-04 11:23
@magic282 I just checked that the RNN examples run well on my windows.

**Comment by magic282** [comment] 2016-07-04 11:27
@sxjscience Yes, the RNN example also runs well here. The s2s with both bucketing and masking code I implemented is the one not working with GPU. So I am not sure if the error was caused by my code or mxnet since my code runs well on CPU.

**Comment by sxjscience** [comment] 2016-07-04 11:30
@magic282 I see. You can try the MShadow PR If you have used `broadcast_mul` or `broadcast_div` in your code.

**Comment by magic282** [comment] 2016-07-04 11:31
Share the code:
```python
def encode(self):
    data = mx.sym.Variable('source')  # input data, source

    # declare variables
    embed_weight = mx.sym.Variable("source_embed_weight")
    param_cells = []
    last_states = []
    for i in range(self.num_of_layer):
        param_cells.append(LSTMParam(i2h_weight=mx.sym.Variable("source_l%d_i2h_weight" % i),
                                     i2h_bias=mx.sym.Variable("source_l%d_i2h_bias" % i),
                                     h2h_weight=mx.sym.Variable("source_l%d_h2h_weight" % i),
                                     h2h_bias=mx.sym.Variable("source_l%d_h2h_bias" % i)))
        state = LSTMState(c=mx.sym.Variable("source_l%d_init_c" % i),
                          h=mx.sym.Variable("source_l%d_init_h" % i))
        last_states.append(state)
    assert (len(last_states) == self.num_of_layer)

    # embedding layer
    embed = mx.sym.Embedding(data=data, input_dim=self.vocab_size + 1,
                             weight=embed_weight, output_dim=self.embed_dim, name='source_embed')
    wordvec = mx.sym.SliceChannel(data=embed, num_outputs=self.seq_len, squeeze_axis=1)

    # split mask
    if self.use_masking:
        input_mask = mx.sym.Variable('source_mask')
        masks = mx.sym.SliceChannel(data=input_mask, num_outputs=self.seq_len, name='sliced_source_mask')

    hidden_all = []
    for seq_idx in range(self.seq_len):
        hidden = wordvec[seq_idx]
        if self.use_masking:
            mask = masks[seq_idx]

        # stack LSTM
        for i in range(self.num_of_layer):
            if i == 0:
                dp_ratio = 0.
            else:
                dp_ratio = self.dropout
            next_state = lstm(self.state_dim, indata=hidden,
                              prev_state=last_states[i],
                              param=param_cells[i],
                              seqidx=seq_idx, layeridx=i, dropout=dp_ratio)

            # process masking
            if self.use_masking:
                prev_state_h = last_states[i].h
                new_h = mx.sym.broadcast_mul(1.0 - mask, prev_state_h) + mx.sym.broadcast_mul(mask, next_state.h)
                next_state = LSTMState(c=next_state.c, h=new_h)

            hidden = next_state.h
            last_states[i] = next_state

        if self.dropout > 0.:
            hidden = mx.sym.Dropout(data=hidden, p=self.dropout)
        hidden_all.append(hidden)

    return hidden_all
```

```python
def decode(self, encoded):
    data = mx.sym.Variable('target')  # target input data
    label = mx.sym.Variable('target_softmax_label')  # target label data

    # declare variables
    embed_weight = mx.sym.Variable("target_embed_weight")
    cls_weight = mx.sym.Variable("target_cls_weight")
    cls_bias = mx.sym.Variable("target_cls_bias")
    init_weight = mx.sym.Variable("target_init_weight")
    init_bias = mx.sym.Variable("target_init_bias")
    input_weight = mx.sym.Variable("target_input_weight")
    input_bias = mx.sym.Variable("target_input_bias")

    param_cells = []
    last_states = []
    init_h = mx.sym.FullyConnected(data=encoded, num_hidden=self.state_dim * self.num_of_layer,
                                   weight=init_weight, bias=init_bias, name='init_fc')
    init_hs = mx.sym.SliceChannel(data=init_h, num_outputs=self.num_of_layer, squeeze_axis=1)
    for i in range(self.num_of_layer):
        param_cells.append(LSTMParam(i2h_weight=mx.sym.Variable("target_l%d_i2h_weight" % i),
                                     i2h_bias=mx.sym.Variable("target_l%d_i2h_bias" % i),
                                     h2h_weight=mx.sym.Variable("target_l%d_h2h_weight" % i),
                                     h2h_bias=mx.sym.Variable("target_l%d_h2h_bias" % i)))
        # state = LSTMState(c=mx.sym.Variable("target_l%d_init_c" % i),
        #                   h=mx.sym.Variable("target_l%d_init_h" % i))
        state = LSTMState(c=mx.sym.Variable("target_l%d_init_c" % i),
                          h=init_hs[i])
        last_states.append(state)
    assert (len(last_states) == self.num_of_layer)

    # embedding layer
    embed = mx.sym.Embedding(data=data, input_dim=self.vocab_size + 1,
                             weight=embed_weight, output_dim=self.embed_dim, name='target_embed')
    wordvec = mx.sym.SliceChannel(data=embed, num_outputs=self.seq_len, squeeze_axis=1)
    # split mask
    if self.use_masking:
        input_mask = mx.sym.Variable('target_mask')
        masks = mx.sym.SliceChannel(data=input_mask, num_outputs=self.seq_len, name='sliced_target_mask')

    hidden_all = []
    for seq_idx in range(self.seq_len):
        con = mx.sym.Concat(wordvec[seq_idx], encoded)
        hidden = mx.sym.FullyConnected(data=con, num_hidden=self.embed_dim,
                                       weight=input_weight, bias=input_bias, name='input_fc')

        if self.use_masking:
            mask = masks[seq_idx]

        # stack LSTM
        for i in range(self.num_of_layer):
            if i == 0:
                dp_ratio = 0.
            else:
                dp_ratio = self.dropout
            next_state = lstm(self.state_dim, indata=hidden,
                              prev_state=last_states[i],
                              param=param_cells[i],
                              seqidx=seq_idx, layeridx=i, dropout=dp_ratio)

            if self.use_masking:
                prev_state_h = last_states[i].h
                new_h = mx.sym.broadcast_mul(1.0 - mask, prev_state_h) + mx.sym.broadcast_mul(mask, next_state.h)
                next_state = LSTMState(c=next_state.c, h=new_h)

            hidden = next_state.h
            last_states[i] = next_state
        # decoder
        if self.dropout > 0.:
            hidden = mx.sym.Dropout(data=hidden, p=self.dropout)
        hidden_all.append(hidden)

    hidden_concat = mx.sym.Concat(*hidden_all, dim=0)
    pred = mx.sym.FullyConnected(data=hidden_concat, num_hidden=self.output_dim,
                                 weight=cls_weight, bias=cls_bias, name='target_pred')

    ################################################################################
    # Make label the same shape as our produced data path
    # I did not observe big speed difference between the following two ways

    label = mx.sym.transpose(data=label)
    label = mx.sym.Reshape(data=label, shape=(-1,))
    if self.use_masking:
        label = label * mx.sym.Reshape(data=input_mask, shape=(-1,))

    # label_slice = mx.sym.SliceChannel(data=label, num_outputs=seq_len)
    # label = [label_slice[t] for t in range(seq_len)]
    # label = mx.sym.Concat(*label, dim=0)
    # label = mx.sym.Reshape(data=label, target_shape=(0,))
    ################################################################################

    sm = mx.sym.SoftmaxOutput(data=pred, label=label, name='target_softmax')

    return sm

```

**Comment by magic282** [comment] 2016-07-04 11:31
@sxjscience Will try the PR.

**Comment by magic282** [comment] 2016-07-04 12:37
@sxjscience BTW, is there any way to accelerate GPU version building progress? It is painfully slow to build it under Windows since it seems that it cannot parallel build.

**Comment by sxjscience** [comment] 2016-07-04 12:40
I'm not familiar with this. Let's ask @hjk41

**Comment by magic282** [comment] 2016-07-04 13:22
@sxjscience Tried. The PR fixed the problem. Thank you!
Env: Windows server 2012, K40m, CUDA 7.0, cudnn v4
mxnet version: eaa5bda94e313b9b6a55a8d8632aff96f0e153ab

**Comment by sxjscience** [comment] 2016-07-04 13:25
@magic282 Seems that this only occurs for K20/K40... The code runs well on 980, Titan X and I don't know the cause...

**Comment by magic282** [comment] 2016-07-04 13:30
@sxjscience Interesting issue. Will is PR merged to the master? We don't have any 980Ti or Titan, only slow Tesla cards. Sad story. And BTW, this problem also occurs for K80... so...

**Comment by sxjscience** [comment] 2016-07-04 13:32
@magic282 I may need to ask other developers about it before merging to the master.

**Comment by sxjscience** [comment] 2016-07-05 04:39
@magic282 The PR has been merged in MShadow.

**Closed by sxjscience** 2016-07-05 04:39 UTC
