### ISSUE TITLE
version `GOMP_4.0' not found/fedora 23

### ISSUE THREAD

**Issue by NiranjanMudhiraj** [dmlc/mxnet#1225] opened 2016-01-09 17:49 UTC
```[niranjan@localhost mxnet]$ python example/image-classification/train_mnist.py ```
```javascript
Traceback (most recent call last):
  File "example/image-classification/train_mnist.py", line 1, in <module>
    import find_mxnet
  File "/home/niranjan/mxnet/example/image-classification/find_mxnet.py", line 7, in <module>
    import mxnet as mx
  File "/home/niranjan/mxnet/example/image-classification/../../python/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/niranjan/mxnet/example/image-classification/../../python/mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "/home/niranjan/mxnet/example/image-classification/../../python/mxnet/base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/home/niranjan/anaconda/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/home/niranjan/anaconda/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libpangoft2-1.0.so.0: undefined symbol: FcWeightToOpenType
```

**Comment by piiswrong** [comment] 2016-01-09 20:43
libpangoft2 is a gnome library. I'm guessing your opencv is not correctly installed/linked. Try compiling with USE_OPENCV=0 and see if the error persists.

**Comment by NiranjanMudhiraj** [comment] 2016-01-10 18:10
i fix that error, but i got another error.

[niranjan@localhost mxnet]$ python example/image-classification/train_mnist.py 
Traceback (most recent call last):
  File "example/image-classification/train_mnist.py", line 1, in <module>
    import find_mxnet
  File "/home/niranjan/mxnet/example/image-classification/find_mxnet.py", line 7, in <module>
    import mxnet as mx
  File "/home/niranjan/mxnet/example/image-classification/../../python/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/niranjan/mxnet/example/image-classification/../../python/mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "/home/niranjan/mxnet/example/image-classification/../../python/mxnet/base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/home/niranjan/anaconda/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/home/niranjan/anaconda/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/niranjan/anaconda/bin/../lib/libgomp.so.1: version `GOMP_4.0' not found (required by /home/niranjan/mxnet/python/mxnet/../../lib/libmxnet.so)

**Comment by thirdwing** [comment] 2016-01-10 18:23
The system needs `GOMP` for openmp support. It seems you need to check it.

**Comment by NiranjanMudhiraj** [comment] 2016-01-10 19:00
libgomp-5.3.1-2.fc23.x86_64 is already installed in my machine.can you tell me how to fix error.

**Comment by thirdwing** [comment] 2016-01-16 16:11
Hi, sorry for the late reply.

I think the OpenMP doesn't install properly on your machine. Can you set `USE_OPENMP = 0` and try again?

If it works, at least we know where the error came from.

**Comment by NiranjanMudhiraj** [comment] 2016-01-16 16:40
can you tell me how to set ```USE_OPENMP = 0```

**Comment by thirdwing** [comment] 2016-01-16 16:43
In the file https://github.com/dmlc/mxnet/blob/master/make/config.mk#L60

**Comment by NiranjanMudhiraj** [comment] 2016-01-16 17:34
i set the ```USE_OPENMP = 0``` , i got following error,

```javascript
[niranjan@localhost mxnet]$ make -j4
  . . . . . . . . . . . . . . . . . . . .
g++ -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv`  -DMXNET_USE_NVRTC=0 -std=c++0x  -o bin/im2rec tools/im2rec.cc build/src/resource.o build/src/io/io.o build/src/io/iter_csv.o build/src/io/iter_image_recordio.o build/src/io/iter_mnist.o build/src/common/tblob_op_registry.o build/src/common/mxrtc.o build/src/ndarray/unary_function.o build/src/ndarray/ndarray_function.o build/src/ndarray/ndarray.o build/src/operator/block_grad.o build/src/operator/embedding.o build/src/operator/pooling.o build/src/operator/cast.o build/src/operator/identity_attach_KL_sparse_reg.o build/src/operator/deconvolution.o build/src/operator/swapaxis.o build/src/operator/softmax_output.o build/src/operator/elementwise_sum.o build/src/operator/lrn.o build/src/operator/convolution.o build/src/operator/cudnn_batch_norm.o build/src/operator/native_op.o build/src/operator/regression_output.o build/src/operator/crop.o build/src/operator/ndarray_op.o build/src/operator/concat.o build/src/operator/activation.o build/src/operator/elementwise_binary_op.o build/src/operator/slice_channel.o build/src/operator/operator.o build/src/operator/batch_norm.o build/src/operator/dropout.o build/src/operator/cross_device_copy.o build/src/operator/softmax_activation.o build/src/operator/elementwise_binary_scalar_op.o build/src/operator/leaky_relu.o build/src/operator/fully_connected.o build/src/operator/upsampling.o build/src/operator/reshape.o build/src/optimizer/optimizer.o build/src/optimizer/sgd.o build/src/engine/naive_engine.o build/src/engine/threaded_engine_pooled.o build/src/engine/threaded_engine.o build/src/engine/engine.o build/src/engine/threaded_engine_perdevice.o build/src/symbol/graph_executor.o build/src/symbol/static_graph.o build/src/symbol/symbol.o build/src/storage/storage.o build/src/c_api/c_predict_api.o build/src/c_api/c_api.o build/src/c_api/c_api_error.o build/src/kvstore/kvstore.o dmlc-core/libdmlc.a -pthread -lm -lsatlas -lrt `pkg-config --libs opencv` 
dmlc-core/libdmlc.a(data.o): In function `dmlc::data::TextParserBase<unsigned int>::TextParserBase(dmlc::InputSplit*, int) [clone ._omp_fn.4]':
data.cc:(.text+0x5): undefined reference to `omp_get_num_procs'
dmlc-core/libdmlc.a(data.o): In function `dmlc::data::TextParserBase<unsigned int>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned int>, std::allocator<dmlc::data::RowBlockContainer<unsigned int> > >*) [clone ._omp_fn.1]':
data.cc:(.text._ZN4dmlc4data14TextParserBaseIjE8FillDataEPSt6vectorINS0_17RowBlockContainerIjEESaIS5_EE._omp_fn.1[_ZN4dmlc4data14TextParserBaseIjE8FillDataEPSt6vectorINS0_17RowBlockContainerIjEESaIS5_EE]+0xd): undefined reference to `omp_get_thread_num'
dmlc-core/libdmlc.a(data.o): In function `dmlc::data::TextParserBase<unsigned int>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned int>, std::allocator<dmlc::data::RowBlockContainer<unsigned int> > >*) [clone ._omp_fn.0]':
data.cc:(.text._ZN4dmlc4data14TextParserBaseIjE8FillDataEPSt6vectorINS0_17RowBlockContainerIjEESaIS5_EE._omp_fn.0[_ZN4dmlc4data14TextParserBaseIjE8FillDataEPSt6vectorINS0_17RowBlockContainerIjEESaIS5_EE]+0x5): undefined reference to `omp_get_num_threads'
dmlc-core/libdmlc.a(data.o): In function `dmlc::data::TextParserBase<unsigned long>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned long>, std::allocator<dmlc::data::RowBlockContainer<unsigned long> > >*) [clone ._omp_fn.2]':
data.cc:(.text._ZN4dmlc4data14TextParserBaseImE8FillDataEPSt6vectorINS0_17RowBlockContainerImEESaIS5_EE._omp_fn.2[_ZN4dmlc4data14TextParserBaseImE8FillDataEPSt6vectorINS0_17RowBlockContainerImEESaIS5_EE]+0x5): undefined reference to `omp_get_num_threads'
dmlc-core/libdmlc.a(data.o): In function `dmlc::data::TextParserBase<unsigned long>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned long>, std::allocator<dmlc::data::RowBlockContainer<unsigned long> > >*) [clone ._omp_fn.3]':
data.cc:(.text._ZN4dmlc4data14TextParserBaseImE8FillDataEPSt6vectorINS0_17RowBlockContainerImEESaIS5_EE._omp_fn.3[_ZN4dmlc4data14TextParserBaseImE8FillDataEPSt6vectorINS0_17RowBlockContainerImEESaIS5_EE]+0xd): undefined reference to `omp_get_thread_num'
dmlc-core/libdmlc.a(data.o): In function `dmlc::data::TextParserBase<unsigned long>::TextParserBase(dmlc::InputSplit*, int) [clone ._omp_fn.5]':
data.cc:(.text._ZN4dmlc4data14TextParserBaseImEC2EPNS_10InputSplitEi._omp_fn.5[_ZN4dmlc4data18CreateLibSVMParserImEEPNS_6ParserIT_EEPKcjj]+0x5): undefined reference to `omp_get_num_procs'
dmlc-core/libdmlc.a(data.o): In function `dmlc::Parser<unsigned int>* dmlc::data::CreateCSVParser<unsigned int>(char const*, unsigned int, unsigned int)':
data.cc:(.text._ZN4dmlc4data15CreateCSVParserIjEEPNS_6ParserIT_EEPKcjj[_ZN4dmlc4data15CreateCSVParserIjEEPNS_6ParserIT_EEPKcjj]+0x7d): undefined reference to `GOMP_parallel'
dmlc-core/libdmlc.a(data.o): In function `dmlc::Parser<unsigned int>* dmlc::data::CreateLibSVMParser<unsigned int>(char const*, unsigned int, unsigned int)':
data.cc:(.text._ZN4dmlc4data18CreateLibSVMParserIjEEPNS_6ParserIT_EEPKcjj[_ZN4dmlc4data18CreateLibSVMParserIjEEPNS_6ParserIT_EEPKcjj]+0x95): undefined reference to `GOMP_parallel'
dmlc-core/libdmlc.a(data.o): In function `dmlc::Parser<unsigned long>* dmlc::data::CreateLibSVMParser<unsigned long>(char const*, unsigned int, unsigned int)':
data.cc:(.text._ZN4dmlc4data18CreateLibSVMParserImEEPNS_6ParserIT_EEPKcjj[_ZN4dmlc4data18CreateLibSVMParserImEEPNS_6ParserIT_EEPKcjj]+0x97): undefined reference to `GOMP_parallel'
dmlc-core/libdmlc.a(data.o): In function `dmlc::data::TextParserBase<unsigned int>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned int>, std::allocator<dmlc::data::RowBlockContainer<unsigned int> > >*)':
data.cc:(.text._ZN4dmlc4data14TextParserBaseIjE8FillDataEPSt6vectorINS0_17RowBlockContainerIjEESaIS5_EE[_ZN4dmlc4data14TextParserBaseIjE8FillDataEPSt6vectorINS0_17RowBlockContainerIjEESaIS5_EE]+0x6a): undefined reference to `GOMP_parallel'
data.cc:(.text._ZN4dmlc4data14TextParserBaseIjE8FillDataEPSt6vectorINS0_17RowBlockContainerIjEESaIS5_EE[_ZN4dmlc4data14TextParserBaseIjE8FillDataEPSt6vectorINS0_17RowBlockContainerIjEESaIS5_EE]+0x157): undefined reference to `GOMP_parallel'
dmlc-core/libdmlc.a(data.o):data.cc:(.text._ZN4dmlc4data14TextParserBaseImE8FillDataEPSt6vectorINS0_17RowBlockContainerImEESaIS5_EE[_ZN4dmlc4data14TextParserBaseImE8FillDataEPSt6vectorINS0_17RowBlockContainerImEESaIS5_EE]+0x6a): more undefined references to `GOMP_parallel' follow
collect2: error: ld returned 1 exit status
Makefile:187: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1
```

**Comment by thirdwing** [comment] 2016-01-16 17:55
I think we can say the problem is from OpenMP.

It is because you are using anaconda, which will link to `GOMP_4.0`. However, in your system you are using gcc5. So you met the error.

Closing this now. Feel free to reopen it.

**Closed by thirdwing** 2016-01-16 17:55 UTC

**Comment by NiranjanMudhiraj** [comment] 2016-01-16 17:58
i set ```USE_OPENMP = 0``` , i tried again it is working without any errors, but python package installation step i got error
```javascript
[niranjan@localhost mxnet]$ cd python/
[niranjan@localhost python]$ sudo python setup.py install
[sudo] password for niranjan: 
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    LIB_PATH = libinfo['find_lib_path']()
  File "mxnet/libinfo.py", line 26, in find_lib_path
    elif os.name == "posix" and os.environ['LD_LIBRARY_PATH']:
  File "/usr/lib64/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'LD_LIBRARY_PATH'
```

**Comment by thirdwing** [comment] 2016-01-16 18:01
The same error with https://github.com/dmlc/mxnet/issues/1283

Please wait for a little while.

**Comment by madcarrot** [comment] 2016-11-27 01:36
I met the same problem, but not sure if my solution applies here. I'm on Ubuntu 16.04 with CUDA 8 and CUDNN v5.1.
```
❯ python train_mnist.py
Traceback (most recent call last):
  File "train_mnist.py", line 1, in <module>
    import find_mxnet
  File "/mnt/raid/user1/Temp/image-classification/find_mxnet.py", line 2, in <module>
    import mxnet as mx
  File "/home/user1/mxnet/python/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/user1/mxnet/python/mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "/home/user1/mxnet/python/mxnet/base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/home/user1/anaconda3/envs/mxnet/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/home/user1/anaconda3/envs/mxnet/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/user1/anaconda3/envs/mxnet/bin/../lib/libgomp.so.1: version `GOMP_4.0' not found (required by /home/user1/mxnet/python/mxnet/../../lib/libmxnet.so)
```

Then I realised that it's looking at a different place for `libgomp.so.1` from what `ldd ~/mxnet/lib/libmxnet.so` says:
```
❯ ldd lib/libmxnet.so | grep libgomp
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f3e30635000)
```

Turns out that those are all just symbolic links to the actual library file `libgomp.so.1.0.0`

so I replaced `/home/user1/anaconda3/envs/mxnet/bin/../lib/libgomp.so.1.0.0` with 1/usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0` and it proceeded to the next error:
```
❯ python train_mnist.py
Traceback (most recent call last):
  File "train_mnist.py", line 1, in <module>
    import find_mxnet
  File "/mnt/user1/rluo/Temp/image-classification/find_mxnet.py", line 2, in <module>
    import mxnet as mx
  File "/home/user1/mxnet/python/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/user1/mxnet/python/mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "/home/user1/mxnet/python/mxnet/base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/home/user1/anaconda3/envs/mxnet/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/home/user1/anaconda3/envs/mxnet/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/user1/anaconda3/envs/mxnet/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/user1/mxnet/python/mxnet/../../lib/libmxnet.so)
```

from here I started to suspect that it's all `anaconda`'s fault...

`ldd ~/mxnet/lib/libmxnet.so` returns 
```
❯ ldd lib/libmxnet.so | grep libstdc++
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fadd0a21000)
```

`/home/user1/anaconda3/envs/mxnet/bin/../lib/libstdc++.so.6` linkes to `libstdc++.so.6.0.19`, while `/usr/lib/x86_64-linux-gnu/libstdc++.so.6` links to `libstdc++.so.6.0.21`

So I copied `libstdc++.so.6.0.21` over and changed the symbolic links, and it seems to work fine now.

**Comment by LukeMathWalker** [comment] 2017-01-08 15:04
I've the same problem and I've not understood how to apply madcarrot solution :/

**Comment by kexul** [comment] 2017-01-17 05:03
Ubuntu 16.10 ,follow the comment ,fisrt changed listdc++,then changed libgomp,then changed pango .It works!

**Comment by Soonhwan-Kwon** [comment] 2017-07-06 07:41
Thank you for great solution @madcarrot 
in summary

ldd lib/libmxnet.so | grep libgomp
rm /your/path/to/anaconda2/lib/libgomp.so.1
ln -s /usr/lib/x86_64-linux-gnu/libgomp.so.1 /home/multi/anaconda2/lib/libgomp.so.1
ldd ~/mxnet/lib/libmxnet.so
rm /your/path/to/anaconda2/bin/../lib/libstdc++.so.6 
ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /home/multi/anaconda2/bin/../lib/libstdc++.so.6 

but please be aware that it differs depends on ldd command result
