### ISSUE TITLE
LSTM bucketing gpu usage

### ISSUE THREAD

**Issue by christallire** [dmlc/mxnet#1644] opened 2016-03-16 06:45 UTC
Hi,
I was testing lstm_pb_bucketing.py and was monitoring GPU usage and found that the model is not utilizing it efficiently
sometimes it does nothing for 1 to 2 seconds, sometimes 22% for a second, sometimes 80% for a second. I think there's problem with minibatch parallelization and I'm guessing it is from doing memory copy or waiting for synchronization or validation.

Testing is done with i7-5820K, GTX970, Windows 10. GPU memory was at 1423MB.

**Comment by pluskid** [comment] 2016-03-16 15:09
Hi @christallire,

Thanks! This might be a potential problem. Could you run the NOT-bucketing version (fixed-length) `lstm_ptb.py` with the same setup and let us know if the GPU usage looks reasonable?

**Comment by christallire** [comment] 2016-03-16 16:46
Hey :)

Yes, it's consistent with 70% usage.

**Comment by piiswrong** [comment] 2016-03-16 21:49
You mean the problem doesn't happen when running without bucketing?

**Comment by christallire** [comment] 2016-03-17 02:16
Yes. correct. but i have doubts that not using up gpu's full potential is right behaviour w/o bucketing

**Comment by pluskid** [comment] 2016-03-17 15:21
The bucketing API has an overhead of doing a hash-table lookup each mini-batch once all the buckets are initialized. I was not expecting a hash-table to be so costly. I briefly tested a while ago by using only 1 bucket and somehow hard-coded it so that hash-table look up goes away, but the speed (number of samples per second) is roughly the same. I did not look at the GPU usage though. 

One extra thing to notice is that the current non-bucketing ptb rnn example is not using the high-level `FeedForward` model API. So the slowness might be deeper somewhere maybe in the `FeedForward` model. Either way, it should be good to locate the performance bug.

I will try to look into this by the weekend. Please let us know if you find out some more information on your side. (e.g. does the GPU usage change a lot in the case of only 1 bucket or a lot buckets, etc.)

**Comment by pluskid** [comment] 2016-03-20 15:32
@christallire Just to clarify, did you test multi-GPU data parallelization or were you using a single GPU? How did you observe the GPU usage? Does the results you observe always easily reproducible?

Just for reference, I did some local test with K80 GPUs, using `nvidia-smi -l 1` to observe the GPU usage. It does varies from ~40% to ~90%, but I did not observe stalling 1 or 2 seconds without doing nothing or only 22% GPU usage.

**Comment by christallire** [comment] 2016-03-20 15:53
@pluskid I was using single GPU w/ 20160309_win10_x64_gpu binary distribution. cuda toolkit and cudnn is also available on the system.
and Yes, It's always easily reproducible, if you want me to run some test, I'll happily do it for you :)

FYI: There's may some concerns about GTX970 cards when memory usage goes up near 3.8GB, performance is reduced due to their memory bus design problem. since I was using only for 1.4GB I think this is not the case.

Thanks!

**Comment by christallire** [comment] 2016-03-20 16:01
Well, I ran a quick test to see the difference between distributions, version 20160309 and 20160229.
Actually, version 20160229 is a lot better! just as you said it varies but stalling is gone.

**Comment by pluskid** [comment] 2016-03-20 16:04
great to hear that! i will still try to do some diagnostics locally to see what caused the varying (my guess is bucket switching and that seems reasonable)

**Comment by pluskid** [comment] 2016-03-20 19:19
@christallire According to my local testing, the bad GPU-usage is mainly due to my naive implementation of the data-iter in that example. I have opened a PR to fix that and now on my local box, the GPU usage is relatively stable ~ 95% now. Once the PR #1681 is merged, could you please have a test of the latest code on your side? (I'm not sure how the Windows distribution is generated, but in this particular case, since only the example file `lstm_ptb_bucketing.py` is updated, you can just download the latest file and replace your local one).

**Closed** 2016-03-22 05:00 UTC

**Comment by christallire** [comment] 2016-03-28 06:03
Works great now :)
