### ISSUE TITLE
nnvm lstm memory issue

### ISSUE THREAD

**Issue by feiyulv** [dmlc/mxnet#3784] opened 2016-11-10 02:18 UTC
The new nnvm branch is faster and cost less gpu memory when seq len is small, but it become slower and cost much more gpu memory when seq len is longer @tqchen 

|      seqlen=100 | nnvm          | master|
| --------------- |:-------------:| -----:|
|  speed(samples/s)|     46.3     | 52.5  |
| memory(MB)      |      8272     | 3609  |

|      seqlen=16  | nnvm          | master|
| --------------- |:-------------:| -----:|
|  speed(samples/s)|     265      | 247   |
| memory(MB)      |      2186     | 2315  |

**Comment by feiyulv** [comment] 2016-11-10 03:32
It seems the grad inplace sum does't work in nnvm branch. I change the `MXNET_EXEC_INPLACE_GRAD_SUM_CAP` value, it affects the gpu memory cost of the master version, but has no influence on nnvm branch

|      seqlen=100 | SUM_CAP=1000 | SUM_CAP=2|
| --------------- |:-------------:| -----:|
|  master|     9198 M   | 3609 M |
| nnvm     |      2256 M     | 2186 M |

@tqchen can you help to check this?

**Comment by tqchen** [comment] 2016-11-10 04:12
The logic of sum cap is here https://github.com/dmlc/mxnet/blob/nnvm/src/executor/graph_executor.cc#L74

**Comment by feiyulv** [comment] 2016-11-10 05:01
@tqchen  thx, have you tested this function?

**Comment by feiyulv** [comment] 2016-11-10 05:24
The old code use the addto_index to share the grads between different nodes
```
 if (grad_source.size() < inplace_sum_cap) {
    gsource = grad_source;
  } else {
    for (size_t i = 1; i < grad_source.size(); ++i) {
      nodes[grad_source[i].source_id]
          .addto_index.push_back(grad_source[i].index);
      nodes[grad_source[i].source_id]
          .inputs.push_back(grad_source[i - 1]);
    }
    gsource.push_back(grad_source.back());
  }
```

```
  // AddTO: always use inplace when addto requirement presents.
  if (node.addto_index.size() != 0) {
    std::vector<std::pair<T, T> > remap(node.addto_index.size());
    const size_t n = node.inputs.size() - node.addto_index.size();
    for (size_t i = 0; i < node.addto_index.size(); ++i) {
      remap[i] = std::make_pair(in_data[n + i],
                                out_data[node.addto_index[i]]);
    }
    return remap;
  }
```

But in nnvm, it simply create a new node  https://github.com/dmlc/mxnet/blob/nnvm/src/executor/graph_executor.cc#L121. I can't figure out how it can realize the grad sum inplace
```
 // use a stream line of plus instead
      nnvm::NodeEntry ret = v[0];
      for (size_t i = 1; i < v.size(); ++i) {
        std::ostringstream os;
        os << "sum_grad_" << i;
        nnvm::NodePtr x = nnvm::Node::Create();
        x->attrs.op = ewise_plus_op;
        x->attrs.name = os.str();
        x->inputs = {ret, v[i]};
        ret = nnvm::NodeEntry{x, 0, 0};
      }
      // identity node is used to avoid exposure of dummy plus node
      // when its output get assigned to another space.
      nnvm::NodePtr id_node = nnvm::Node::Create();
      id_node->attrs.op = identity_op;
      id_node->attrs.name = "sum_grad_final";
      id_node->inputs = {ret};
      return nnvm::NodeEntry{id_node, 0, 0};
```

**Comment by feiyulv** [comment] 2016-11-10 08:10
I print the gwmat.dptr_ of h2h fully-connected operator, seq len is 16, only the seq id  of 15, 14, 0 shares the same memory. This maybe a bug of nnvm. Hope you can help to verify @tqchen 
![img_20161110_155230](https://cloud.githubusercontent.com/assets/18651286/20168845/1d6b8a08-a75f-11e6-9968-0f5c3f9eb2dc.jpg)

**Comment by feiyulv** [comment] 2016-11-10 09:33
https://github.com/dmlc/mxnet/blob/nnvm/src/executor/inplace_addto_detect_pass.cc#46
```
 if (inode.inputs[0].node_id >= inode.inputs[1].node_id) continue;
```
the logic of the code above  is not right, since in most case inputs[0].node_id is larger than inputs[1].node_id
```
       nnvm::NodePtr x = nnvm::Node::Create();
        x->attrs.op = ewise_plus_op;
        x->attrs.name = os.str();
        x->inputs = {ret, v[i]};
```
maybe we can remove this line

**Comment by tqchen** [comment] 2016-11-10 20:33
the node id is mainly for the correct ordering, because we indeed relies on the node_id ordering for the summation( the first assignment need to come first). Due to the topo sort nature of and reverse topo traversal, this condition could be in general satisfied, but maybe I am missing somehting here

**Comment by feiyulv** [comment] 2016-11-11 01:02
maybe what you want to express is:
```
if ((inode.inputs[0])->inputs[1]).node_id >= inode.inputs[1].node_id) continue;
```
since `inode.inputs[0] ` is a new created `ewise_plus_op` for most case, except the first node, see follows:
```
 // use a stream line of plus instead
      nnvm::NodeEntry ret = v[0];
      for (size_t i = 1; i < v.size(); ++i) {
        std::ostringstream os;
        os << "sum_grad_" << i;
        nnvm::NodePtr x = nnvm::Node::Create();
        x->attrs.op = ewise_plus_op;
        x->attrs.name = os.str();
        x->inputs = {ret, v[i]};
        ret = nnvm::NodeEntry{x, 0, 0};
      }
      // identity node is used to avoid exposure of dummy plus node
      // when its output get assigned to another space.
      nnvm::NodePtr id_node = nnvm::Node::Create();
      id_node->attrs.op = identity_op;
      id_node->attrs.name = "sum_grad_final";
      id_node->inputs = {ret};
      return nnvm::NodeEntry{id_node, 0, 0};
```

**Comment by feiyulv** [comment] 2016-11-14 09:40
https://github.com/dmlc/mxnet/blob/nnvm/src/executor/inplace_addto_detect_pass.cc#46
Even removing this line, nnvm still costs a little more gpu memory than the master version. What's worse, there is no speed improvement for bucket lstm, actually the speed drops.

**Comment by tqchen** [comment] 2016-12-04 21:40
I take a look at this problem today. This was due to the topological sort issue of LSTM. Traditionally, the topological order of backward pass is always the reverse order of the forward pass. This means the forward traditionally goes from left to right, down to up, and the backward goes in the reverse direction.  

In the NNVM pass, there is no strict order of backward pass, which goes by PostOrderDFS, with the gradient out and the softmax as head.
So what happened is follow

The current graph have
```
Embedding -> SliceChannel
                          -> t0_i2h -> t0 LSTM
                                         |
                             t1_i2h -> t1 LSTM
```
In the gradient calculation pass, we do postDFS for embedding_weight_grad, which requires SliceChannel grad, and requires t0_i2h_backward and t1_i2h_backward.
Note that because there is no dependency between t0_i2h and t1_i2h, they can be ordered arbitrarily, and in this case, they are ordered to be t0, t1, while the
ideal case should have been t1 t0.

To fix this case, we will be adding a control flow dependency in the sum aggregation nodes, when there is no existing order between them, to ensure that the order is enforced.

**Comment by tqchen** [comment] 2016-12-04 21:44
@feiyulv  can you see if it fixes the problem? It should fix the memory problem. I am not sure for speed also cc @feiyulv @Ldpe2G

**Comment by tqchen** [comment] 2016-12-04 21:46
Let us also follow up on the speed difference. The speed difference could have also been caused by bulk execution, it is easy to verify if that is the case in master via disable the bulk execution.

**Comment by Ldpe2G** [comment] 2016-12-05 01:33
@tqchen I have tested the nnvm branch lstm example after the change #4093 and now the speed is the same as master .

**Comment by feiyulv** [comment] 2016-12-05 05:44
@tqchen  Wonderful, both the memory and the speed is almost the same as the master now.

**Comment by tqchen** [comment] 2016-12-05 10:48
great, so the cause is mainly due to the execution order, I think we can safely close this issue then. Thanks!

**Closed by tqchen** 2016-12-05 10:48 UTC
