### ISSUE TITLE
strange core dumped problem

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#510] opened 2015-11-07 11:08 UTC
Code:
```python
def test2():
    data_in = mx.symbol.Variable('data')
    conv = mx.symbol.Convolution(data=data_in, kernel=(3, 3), num_filter=16)
    datatmp = np.ones((1, 1, 32, 64))
    mxdata = mx.nd.array(datatmp)
    weightmp = np.ones((16, 1, 3, 3))
    mxweight = mx.nd.array(weightmp)
    biastmp = np.zeros(16)
    mxbias = mx.nd.array(biastmp)
    exe_c = conv.bind(ctx=mx.cpu(), args=[mxdata, mxweight, mxbias])
    out = exe_c.forward()
    
test2()
```
Error result:
```
terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted
Aborted (core dumped)
```

**Comment by hotpxl** [comment] 2015-11-08 01:25
I'm not quite sure how the environment is set up. It's possible you are not linked against pthread. Make sure you have `-pthreads` in the compile options.

**Comment by starimpact** [comment] 2015-11-08 05:04
It is not possible, I compiled the mxnet without changing anything.Just used default setting.

**Comment by lukemetz** [comment] 2015-11-14 19:29
I ran into the same problem with slightly different code:
```python
import mxnet as mx

x = mx.sym.Variable("x")
y = mx.sym.sqrt(x)

with mx.cpu(0) as ctx:
    executor = y.simple_bind(ctx, x=(1,))
    executor.arg_arrays[0][:] = 4
    executor.forward()
    out_var = executor.outputs[0]
    print out_var
    print out_var.asnumpy()

    mx.ndarray.waitall()
    print "done"
```

It appears to be a race condition when the python program exits. It only happens half the time and can be fixed with a breakpoint  and then manually continuing just before exit. The result is always printed even on crash.

**Comment by tqchen** [comment] 2015-11-14 19:34
hmm, can you try to get some stack trace on such error, so we can have a general idea on where things went wrong, thanks!

**Comment by lukemetz** [comment] 2015-11-14 19:51
I tried, was hoping to be a little more useful. Do you know how?
I tried compiling with -rdynamic, DEBUG=1.
When running under GDB everything seems to just work. I will play around some more and see if I can get one.

**Comment by tqchen** [comment] 2015-11-14 19:54
I was thinking about gdb, don't have brilliant idea on this:( thanks for investigating and please let us know if you have more fundings

**Comment by lukemetz** [comment] 2015-11-14 20:11
So this appears to be a bug with openblas as when compiling with normal blas the error does not occur. Also, the following code is a minimal example to reproduce the bug. Still no stack trace.
```python
import mxnet as mx
```

**Comment by pluskid** [comment] 2015-11-14 20:55
The original post mentioned that there is a core dumped. If you actually get a core file dumped, you can load the core file into GDB, and get some stack trace. Although when the libraries are not compiled with `-g`, the stack trace might be hard to decrypt (e.g. fully of `???` or might be even misleading).

**Comment by lukemetz** [comment] 2015-11-14 21:05
Didn't know you could do that.
I set `ulimit -c unlimited` to get a core file to show up,
then gdb that file. all ??? on backtrace, no symbols despite mxnet with -g. I checked each of the 4 available frames and none had symbols.

I think its in the ThreadEnginePerDevice dealloc method.
I annotated the code with the following:
```c++
    printf("A\n");
    gpu_normal_workers_.Clear();
    printf("B\n");
    gpu_copy_workers_.Clear();
    printf("C\n");
    cpu_normal_workers_.Clear();
    printf("D\n");
    cpu_priority_worker_.reset(nullptr);
    printf("Dealloc threadedEgninginePer\n");
```
With a result of
```
$ MXNET_ENGINE_TYPE=ThreadedEnginePerDevice python test.py 
[16:02:50] src/engine/engine.cc:36: MXNet start using engine: ThreadedEnginePerDevice
A
B
C
D
terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted
Aborted (core dumped)
```

I am kinda a noob when it comes to debugging this stuff, but I will update if I can get something working. Thanks for the help!

**Comment by pluskid** [comment] 2015-11-14 21:45
just for the record, I also noticed some crashing from Julia side recently. Basically, if I only load libmxnet but does not do any computation with it. Something like
```julia
using MXNet

for i = 1:5
  println(i)
end
```
then it will crash:
```
1
2
3
4
5
fish: 'julia foo.jl' terminated by signal SIGSEGV (Address boundary error)
```

But it will not crash if I actually did some computation (e.g. train a neural network) with MXNet. I have not been able to spend time to debug this yet.

**Comment by korneil** [comment] 2015-11-22 00:26
Here is a backtrace with source "import mxnet":

    # gdb python core
    GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
    Copyright (C) 2014 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-linux-gnu".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>.
    Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
    For help, type "help".
    Type "apropos word" to search for commands related to "word"...
    Reading symbols from python...(no debugging symbols found)...done.

    warning: core file may not match specified executable file.
    [New LWP 2344]
    [New LWP 2338]
    [New LWP 2340]
    [New LWP 2339]
    [New LWP 2341]
    [New LWP 2342]
    [New LWP 2337]
    [New LWP 2345]
    [New LWP 2343]
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    Core was generated by `python perceptron.py'.
    Program terminated with signal SIGABRT, Aborted.
    #0  0x00007fd976499cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
    56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    Traceback (most recent call last):
      File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
        from libstdcxx.v6.printers import register_libstdcxx_printers
    ImportError: No module named 'libstdcxx'
    (gdb) info threads
      Id   Target Id         Frame
      9    Thread 0x7fd94a629700 (LWP 2343) clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:81
      8    Thread 0x7fd949627700 (LWP 2345) __lll_lock_wait_private ()
        at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:95
      7    Thread 0x7fd976c3e740 (LWP 2337) 0x00007fd97683166b in pthread_join (threadid=140571240998656,
        thread_return=0x0) at pthread_join.c:92
      6    Thread 0x7fd94ae2a700 (LWP 2342) clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:81
      5    Thread 0x7fd94cdce700 (LWP 2341) 0x00007fd97655012d in poll () at ../sysdeps/unix/syscall-template.S:81
      4    Thread 0x7fd97066c700 (LWP 2339) 0x00007fd97652e3f7 in sched_yield ()
        at ../sysdeps/unix/syscall-template.S:81
      3    Thread 0x7fd96fe6b700 (LWP 2340) 0x00007fd97652e3f7 in sched_yield ()
        at ../sysdeps/unix/syscall-template.S:81
      2    Thread 0x7fd970e6d700 (LWP 2338) 0x00007fd97652e3f7 in sched_yield ()
        at ../sysdeps/unix/syscall-template.S:81
    * 1    Thread 0x7fd949e28700 (LWP 2344) 0x00007fd976499cc9 in __GI_raise (sig=sig@entry=6)
        at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
    (gdb) bt
    #0  0x00007fd976499cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
    #1  0x00007fd97649d0d8 in __GI_abort () at abort.c:89
    #2  0x00007fd95f179535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #3  0x00007fd95f1776d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #4  0x00007fd95f177703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #5  0x00007fd95f1caad5 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #6  0x00007fd976830182 in start_thread (arg=0x7fd949e28700) at pthread_create.c:312
    #7  0x00007fd97655d47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
    (gdb)

**Comment by pluskid** [comment] 2015-11-23 04:33
@korneil It seems to be an import error. Can you confirm that this error occur only when you have a script file containing nothing but
```
import mxnet
```
and yet you can run the built-in examples without problem (e.g. mnist/mlp.py)?

**Comment by tqchen** [comment] 2015-12-15 04:20
closing due to inactive status, feel free to reopen if there is update

**Closed** 2015-12-15 04:25 UTC
