### ISSUE TITLE
all optimisers except sgd not working in R

### ISSUE THREAD

**Issue by boofhead** [dmlc/mxnet#3603] opened 2016-10-24 17:51 UTC
Training fails to start with following error:

Error in eval(substitute(expr), envir, enclos) :
      expecting an external pointer

I have looked through the r code for all the optimisers and I don't see any reason it should work for 'sgd' but not any of the others.

**Comment by boofhead** [comment] 2016-10-24 21:40
Well, not as easily as I thought. Seems like the problem is using multiple gpu except in my toy script even sgd gives the error.

`library(mxnet)

X <- as.matrix(iris[,1:4])
y <- as.integer(iris[,5] == 'virginica')

data <- mx.symbol.Variable('data')
data <- mx.symbol.FullyConnected(data, num_hidden = 1)
data <- mx.symbol.Activation(data, act_type = 'tanh')
logreg <- mx.symbol.LogisticRegressionOutput(data)

model <- mx.model.FeedForward.create(logreg, X, y, learning.rate = 0.1)

model2 <- mx.model.FeedForward.create(logreg, X, y, optimizer = 'adam')

n.gpu <- 1
devices <- lapply(0:(n.gpu-1), function(i) {
  mx.gpu(i)
})
model3 <- mx.model.FeedForward.create(logreg, X, y, ctx=devices, optimizer = 'adam')

n.gpu <- 4
devices <- lapply(0:(n.gpu-1), function(i) {
  mx.gpu(i)
})
model4 <- mx.model.FeedForward.create(logreg, X, y, ctx=devices, optimizer = 'sgd', learning.rate=0.1)
model5 <- mx.model.FeedForward.create(logreg, X, y, ctx=devices, optimizer = 'adam')` 

`Error in eval(substitute(expr), envir, enclos) : 
  expecting an external pointer`

**Comment by thirdwing** [comment] 2016-11-04 15:32
@boofhead Really sorry for the late reply.

Since currently I only have access to one-GPU machine, it is hard for me to reproduce this. I will take a look into it later.

**Comment by miguelgfierro** [comment] 2016-12-11 08:09
Had the same problem. The error was because I was using an R array instead of a `MXNDArray`. To transform from array to `MXNDArray`: `mxnet:::as.array.MXNDArray(arr)`

**Comment by miguelgfierro** [comment] 2016-12-11 19:22
The error might be related to #4184. You may have an array that should be converted to `MXNDArray`

**Comment by boofhead** [comment] 2016-12-11 21:05
No, mx.modelFeedforward.create should detect an R array and create an `mx.nd.array` iter. Has code to do that and works fine on one gpu.

**Comment by thirdwing** [comment] 2017-07-15 01:17
This should be fixed in #7056

**Closed** 2017-07-15 05:18 UTC
Labels: R-Package
