### ISSUE TITLE
how to remove the uninitialized warning?

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#593] opened 2015-11-16 08:37 UTC
```
./mshadow/mshadow/tensor.h: In function ‘void mshadow::MapExp(mshadow::TRValue<R, mshadow::gpu, dim, DType>*, const mshadow::expr::Exp<E, DType, etype>&) [with Saver = mshadow::sv::saveto; R = mshadow::Tensor<mshadow::gpu, 2, float>; int dim = 2; DType = float; E = mshadow::expr::BinaryMapExp<mshadow::op::minus, mshadow::expr::BinaryMapExp<mshadow::op::div, mshadow::Tensor<mshadow::gpu, 2, float>, mshadow::expr::BinaryMapExp<mshadow::op::plus, mshadow::Tensor<mshadow::gpu, 2, float>, mshadow::expr::ScalarExp<float>, float, 1>, float, 1>, mshadow::expr::BinaryMapExp<mshadow::op::div, mshadow::expr::BinaryMapExp<mshadow::op::minus, mshadow::expr::ScalarExp<float>, mshadow::Tensor<mshadow::gpu, 2, float>, float, 1>, mshadow::expr::BinaryMapExp<mshadow::op::plus, mshadow::expr::BinaryMapExp<mshadow::op::minus, mshadow::expr::ScalarExp<float>, mshadow::Tensor<mshadow::gpu, 2, float>, float, 1>, mshadow::expr::ScalarExp<float>, float, 1>, float, 1>, float, 1>; int etype = 1]’:
./mshadow/mshadow/tensor.h:67:1: warning: ‘shape2.mshadow::Shape<2>::shape_[1u]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       this->shape_[i] = s[i];
 ^
./mshadow/mshadow/././expr_engine-inl.h:361:13: note: ‘shape2’ was declared here
     Shape<dim> shape2 = ShapeCheck<dim, TB>::Check(t.rhs_);
             ^

```

**Comment by starimpact** [comment] 2015-11-16 08:38
the following code creates the up warning:
```python
    tdata_out = F<mshadow_op::log>(tdata_in + MIN_NUM) * tlabel +
                (1.0f - tlabel) * F<mshadow_op::log>(1.0f - tdata_in + MIN_NUM);
    tdata_out = tdata_out * tmarklabel * -1;
```

**Comment by starimpact** [comment] 2015-11-16 08:39
I think the expression has no problem. 
But how it to cause the warning?

**Comment by tqchen** [comment] 2015-11-18 04:32
Likely because some source of your tensor's shape was not intialized?

**Comment by starimpact** [comment] 2015-11-18 13:12
I don't think it can work when any tensor's shape was not initialized. isn't it?
tensor must have shape or cannot exist.

**Comment by starimpact** [comment] 2015-11-18 13:14
I don't think it can work when any tensor's shape was not initialized. isn't it?
tensor must have shape, otherwise it cannot exist.

**Comment by starimpact** [comment] 2015-11-19 21:25
@tqchen

**Comment by starimpact** [comment] 2015-11-19 21:26
@piiswrong

**Comment by starimpact** [comment] 2015-11-19 21:27
@vchuravy

**Comment by piiswrong** [comment] 2015-11-19 21:43
Please send a minimal configuration that reproduces this warning
https://gist.github.com/

**Comment by tqchen** [comment] 2015-11-19 22:11
@starimpact The best way to get help is to ***paste something that others can reproduce***, like a snippet that can be compiled  and produces the warning you mentioned. Otherwise, it is very hard for others to help you, as guessing the context of what might happened on your side, so hard for others to take actions, and reply to your issue.


This warning is quite clear, saying that there is an assignment, and source shape array of the assignment might not be initialized.  This is likely due to for example, shape array of ```t_data``` or ```t_label``` are not completely initialized. Check how did you created the ```t_data``` and ```t_label```, if some shape content you used was not initialized.

**Comment by tqchen** [comment] 2015-11-19 22:26
For example, a better way on raising the issue could be something like

The following code gives the warning blabla, and there appears to be nothing wrong on this code, etc.
```
#include <mshadow/tensor.h>

int main() {
   mshadow::Tensor<cpu, 2> data = mshadow::NewTensor<cpu, 2>(Shape2(1, 2));
   mshadow::Tensor<cpu, 2> out = mshadow::NewTensor<cpu, 2>(Shape2(1, 2));
   data = 0.1f;
   float MIN_NUM = 3.0
    out = F<mshadow_op::log>(data + MIN_NUM) * data +
                (1.0f - data) * F<mshadow_op::log>(1.0f - data + MIN_NUM);
    return 0;
}
```
In this way, others can directly copy this snippet, reproduce the warning they had, and fix the potential problem. If you cannot get the snippet that reproduces the error, think about the difference between the snippet version and the code you have, is there any gap that causes the problems?

There are two types of issues that the developers can and will effectively answer
- A snippet that is minimal and reproducible which indicates some problems
- A question regard to the system, i.e. "can we read element data from GPU tensor"
   - The answer will be yes or no.

The question such as "I have this snippet of code that seems to be wrong, but I do not know why" is hard to take action, and usually will be ignored due to this reason

**Comment by starimpact** [comment] 2015-11-19 23:36
😄

**Comment by tornadomeet** [comment] 2015-11-20 01:33
i also find that when compile the newest offical mxnet(without any change), it will report this uninitialized warning.

**Comment by piiswrong** [comment] 2015-11-20 04:33
fixed by https://github.com/dmlc/mxnet/pull/643

**Closed** 2015-11-20 04:33 UTC
