### ISSUE TITLE
Build Fail on Ubuntu Linux from today

### ISSUE THREAD

**Issue by pouya-cognitiv** [dmlc/mxnet#2128] opened 2016-05-13 07:33 UTC
I pulled today and attempted to build with:
USE_CUDA = 1
USE_CUDA_PATH = /usr/local/cuda-7.0

Attached is the build output:
[build fail.txt](https://github.com/dmlc/mxnet/files/262707/build.fail.txt)

The most recent tag (20160419) builds fine.

**Comment by tornadomeet** [comment] 2016-05-13 08:50
@pouya-cognitiv  this may due to the makefile changed recently #2109 ,you can change back and rebuild again.

@tqchen @antinucleon @winstywang @piiswrong du to the change #2109 , the newest mxnet will fail when build, and **all the recently pull request failed** is the same reason, so it seems that in lru.cu nees use ```--use_fast_math``` to build.

**Comment by antinucleon** [comment] 2016-05-13 08:57
@tornadomeet Which CUDA version are you using? I am suing CUDA 8.0 and 7.5, both works well.

**Comment by tornadomeet** [comment] 2016-05-13 09:02
@antinucleon  here is CUDA-7.0, it shoud be the cuda version.

**Comment by antinucleon** [comment] 2016-05-13 09:25
@pouya-cognitiv @tornadomeet I find out nvcc-7.0 segfault in compile lru.cu. I will find a machine with cuda 7.0 to check how to avoid it.

**Comment by tornadomeet** [comment] 2016-05-13 09:28
cool

**Comment by antinucleon** [comment] 2016-05-13 10:47
I "pretend" to fix it in: https://github.com/dmlc/mxnet/pull/2134
The problem is caused by old nvcc expanding template. As LRN is not widely used, I think currently we can ignore it.

**Comment by tornadomeet** [comment] 2016-05-13 11:13
looks good to me

**Comment by antinucleon** [comment] 2016-05-13 20:52
Should be fixed by pulling newest code.

**Closed by antinucleon** 2016-05-13 20:52 UTC
