### ISSUE TITLE
Question about simple matrix operations using cpp api

### ISSUE THREAD

**Issue by cogons** [dmlc/mxnet#6153] opened 2017-05-08 07:13 UTC
Inspired by the example in python:

```
    A = mx.symbol.Variable('A')
    B = mx.symbol.Variable('B')
    C = A * B
    a = mx.nd.ones(3) * 4
    b = mx.nd.ones(3) * 2
    c_exec = C.bind(ctx=mx.cpu(), args={'A' : a, 'B': b})
    c_exec.forward()
    c_exec.outputs[0].asnumpy()
    [ 8.  8.  8.]
```
I'm trying to write a simple matrix plus in cpp like this:

```
    Context ctx = Context::cpu();
    Symbol a = Symbol::Variable("a");
    Symbol b = Symbol::Variable("b");
    auto c = _Plus(a,b);
    std::map<string, NDArray> args;
    std::vector<mx_float> ac(2);
    ac[0] = 1.0;
    ac[1] = 2.0;
    std::vector<mx_float> bc(2);
    bc[0] = 1.0;
    bc[1] = 2.0;
    args["a"] = NDArray(ac,Shape(2), ctx);
    args["b"] = NDArray(bc,Shape(2), ctx);
    NDArray::WaitAll();
    auto *exec = c.SimpleBind(ctx, args);
    exec->Forward(false);
    auto x = exec->outputs[0].Reshape(Shape(2)).GetData()[0];
    NDArray::WaitAll();
    delete exec;
    MXNotifyShutdown();
    cout<<x<<endl;
```

when i run this piece of code, the output is a random number(nearly zero, like 2.19945e-38, 1.16171e-38...).

My question is .. how to write a symbol to perform simple matrix plus properly using mxnet c++ api?

It seems to be a stupid question. : (

Thanks in advance.

**Comment by lx75249** [comment] 2017-05-08 07:41
You should move `NDArray::WaitAll()` before x is evaluated, because after you call `exec->Forward()`, the value of its output will be cacluated asynchronously.

**Comment by cogons** [comment] 2017-05-08 08:06
@lx75249 Thanks. I did what you advised, but i still get random number close to zero. :(

i'm wondering if the process is incomplete or wrong..

**Comment by lx75249** [comment] 2017-05-08 08:37
@cogons I forgot that you should also remove reshape... or waitall after reshape

**Comment by cogons** [comment] 2017-05-08 08:49
@lx75249 still the same symptom.. 

BTW, is it a good way to monitor ndarray output like this?
 `exec->outputs[0].GetData()[0];`

**Comment by lx75249** [comment] 2017-05-08 08:50
@cogons cannot reproduce. Could you paste complete code?

**Comment by cogons** [comment] 2017-05-08 08:51
@lx75249 

```

#include <iostream>
#include <fstream>
#include <map>
#include <string>
#include <vector>
#include "mxnet-cpp/MxNetCpp.h"
#include "../include/mxnet-cpp/op.h"

using namespace std;
using namespace mxnet::cpp;

int main(int argc, char const *argv[])
{
  mxnet::cpp::Context ctx = mxnet::cpp::Context::cpu();
  auto shape = Shape(2);
  Symbol a = Symbol::Variable("a");
  Symbol b = Symbol::Variable("b");
  auto c = a+b;
  std::map<string, NDArray> args;
  std::vector<mx_float> ac(2);
  ac[0] = 1.0;
  ac[1] = 2.0;
  std::vector<mx_float> bc(2);
  bc[0] = 1.0;
  bc[1] = 2.0;
  args["a"] = NDArray(ac,shape, ctx);
  args["b"] = NDArray(bc,shape, ctx);
  auto *exec = c.SimpleBind(ctx, args);
  exec->Forward(false);
  auto x = exec->outputs[0].GetData()[0];
  MXNotifyShutdown();
  delete exec;
  cout<<x<<endl;
  return 0;
}
```

**Comment by lx75249** [comment] 2017-05-08 08:56
I said you should use waitall before GetData(), like this
```cpp
  exec->Forward(false);
  NDArray::WaitAll();
  auto x = exec->outputs[0].GetData()[0];
```

About monitor, it has been implemented but is under review. You can use this for now, but after monitor is merged, you are recommended to use the monitor provided in cpp-package. Outputing ndarray to `std::ostream` will also be supported by then.

**Comment by cogons** [comment] 2017-05-08 09:00
@lx75249  It works. Much thanks!!

**Closed** 2017-05-08 09:05 UTC
