### ISSUE TITLE
better test

### ISSUE THREAD

**Issue by mli** [dmlc/mxnet#1075] opened 2015-12-26 05:39 UTC
hi guys,

since we are getting more and more contributors, it's quite necessary to improve our test cases. i'm starting to work on it, here is what i thought. any comment is welcome

## test servers 

1. use travis only for building test, since it is slow. but it's still valuable since supporting mac osx and easy to use
2. we are gonna to run our building service (probably [jekins](jenkins-ci.org)) on a dedicated machine with two gpus, so we can run more expensive end-to-end tests

## test cases

i suggest to make three folds in tests/

1. `unit-test`  for fast unit tests
2. `end-to-end-test` for testing the whole system on small datasets, e.g train_mnist or train_cifar10
3. `release-test` to test our main application examples, e.g. train_imagenet.py. it's quite expensive so we only run it before each release, and probably use powerful machines e.g. 4 titan x 

## data service

setup a web service for easy sharing data with 10G - 100G scales. 

## versioned release

i suggest we do [versioning](http://semver.org/) since users may like well tested releases, rather than `git pull` and then found some broken

**Comment by piiswrong** [comment] 2015-12-26 06:08
This is a good idea. A few suggestions:
1) I also think travis is getting too slow. We should try to move as many things as possible out of it. 
2) How about regression-test instead of end-to-end test.
3) Can we also host models with it? People are having trouble downloading models as LFS runs out of quota.
4) I like the idea of versioned release. we can probably release them as branches so it's easier to make hot fixes after release.

**Comment by mli** [comment] 2015-12-26 22:41
unit and system (or end-to-end) are test levels, https://en.wikipedia.org/wiki/Software_testing#Testing_levels while regression refers to the test types. so we probably use a fold called `system` since `end-to-end` means something else in deep learning.

the models are hosted on amazon s3 now, will move to the data service when it is ready

using branches for release may results a lot of branches on github. one often uses the tags for releasing,  see https://github.com/dmlc/MXNet.jl/releases, but yes, it makes hotfix not so straightforward. @pluskid any ideas?

**Comment by pluskid** [comment] 2015-12-26 22:57
I would suggest using tags for releasing instead of branches. I think we can have major.minor.bugfix release versioning scheme and release more frequently when relatively major bugfixes are merged. I oppose using branches as releases because I feel it is very unmanageable if we want to back port bug fixes to every release branches. If there is no agreement on git workflows, we could probably try to follow some well established workflows such as [git flow](http://nvie.com/posts/a-successful-git-branching-model/) for a random example.

Travis CI could have [dedicated building servers](https://travis-ci.com/plans). The plan is quite expensive ($129/month). But github has an [education pack](https://education.github.com/pack), and private builds for Travis CI are available as long as you are a student. I have never tried to set that up. Maybe we could try to utilize that instead of setting up our own CI server (unless setting up is very easy and still integrate well with github).

In any case, I support splitting test cases into fast unit-test and deeper tests. I think it is a good idea to add coverage statistics. Currently MXNet.jl is using [codecov](https://codecov.io/github/dmlc/MXNet.jl?branch=master). I guess this might be a bit tricky as the main repo is actually a host of a lot of front-ends.

**Comment by mli** [comment] 2015-12-26 23:28
i tried codecov, unfortunately our python unittest's coverage is below 40%...

i'm trying to ensemble a build machine with two gpus, so we can do some easy end-to-end gpu tests for each push.

**Comment by tqchen** [comment] 2015-12-27 00:54
+1 for versioned release as @pluskid suggested, we might need a dedicated machine for the regression test.

**Closed** 2016-05-07 04:06 UTC
Labels: enhancement
