### ISSUE TITLE
faild to get a single value of a tensor in gpu

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#642] opened 2015-11-19 21:50 UTC
@tqchen @piiswrong why does it exist ? is it a bug of mxnet or mshadow ?

**Comment by tqchen** [comment] 2015-11-19 22:03
Can you be more specific? i.e, provide a snippet that produces your problem. If you mean directly get element from gpu into a float variable. It is indeed not possible, because the content of that float do not sit on main memory, and the instruction is not aware of that, an explicit copy to CPU is needed

**Comment by starimpact** [comment] 2015-11-20 13:50
matrix divided by a scalar(this is a element from a tensor vector) should be supported in gpu. i think so.

**Comment by starimpact** [comment] 2015-11-20 13:55
i.e. M is a matrix tensor, V is a vector tensor.
expression ```M/V[i]``` will be failed in gpu, but will be successful in cpu.
as well as ```std::cout<<V[i]```.

**Comment by tqchen** [comment] 2015-11-20 18:06
The problem is on ```V[i]```, reading i-th element from the vector. Which is not supported. For a compiler, this means get the value from address ```v.data+i```. And the compiler do not know the address is on GPU.

Note that all scalars(floats) sits on registers on CPU, so in order to do that, we need to copy the value from ```v.data+i``` to CPU, e.g. by allocating a length-1 vector cpu tensor.

So you can do ```M/3.0f``` expression, or  ```M/a``` where a is a float(whichi sits on CPU)

**Comment by starimpact** [comment] 2015-11-20 21:17
do you mean ```M/3.0f```is also only work on CPU?
so the only way to make this type expression work on gpu is to fill 3.0f to a matrix which is same size to M.
but the question is whether the generation of matrix of value 3.0f could be finished on gpu ?

**Comment by tqchen** [comment] 2015-11-20 23:29
You can try it out, ```M / 3.0f``` works on GPU. The point is that the ```3.0f``` sits on CPU. 

The problem you encountered is due to  operation  ```float a =  V[i]```. Which compiler treats as a CPU memory load. So you will need to copy V[i] back to CPU first

**Comment by starimpact** [comment] 2015-11-21 01:08
does it affect the performance?

**Comment by tqchen** [comment] 2015-11-21 01:11
It only involves copy of small amount of data back to CPU, so presumably no

**Comment by tqchen** [comment] 2015-11-21 02:02
closing for now as the question get answered

**Closed by tqchen** 2015-11-21 02:02 UTC
