### ISSUE TITLE
Strange behavior of CSVIter

### ISSUE THREAD

**Issue by EasonD3** [dmlc/mxnet#2248] opened 2016-05-26 04:44 UTC
I have this very simple test case: https://github.com/EasonD3/mxnet-csviter-issue. It basically loads integers `1, ..., 10` from a CSV file by using `mx.io.CSVIter`. To check if each batch (denoted as `batch`) is generated correctly, I tried to print out some information (e.g., `len(batch.data[0].asnumpy())`, `batch.pad`).

I run [`test_csviter.py`](https://github.com/EasonD3/mxnet-csviter-issue/blob/master/test_csviter.py) as in the above mentioned repo for several times, by setting `batch_size = 3`. The printed outputs should be expected to be the same. However, it turns out that they are not the same. Specifically, below are the two different outputs (kindly note that I've tested on several machines and they all produced those different outputs):

**First:**
```
* batch 1: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 3.]
 [ 4.]
 [ 5.]]

* batch 2: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 6.]
 [ 7.]
 [ 8.]]

* batch 3: len(data[0]) = 3, b.pad = 1
data[0]:
[[  9.]
 [ 10.]
 [  1.]]
```
**Second:**
```
* batch 1: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 1.]
 [ 2.]
 [ 3.]]

* batch 2: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 4.]
 [ 5.]
 [ 6.]]

* batch 3: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 7.]
 [ 8.]
 [ 9.]]

* batch 4: len(data[0]) = 3, b.pad = 2
data[0]:
[[ 10.]
 [  1.]
 [  2.]]
```

Rationally, the second output should be the correct one (I did reset the iter every time when I ran the code). But I have no idea how and why it also produces the first output. Shouldn't it always start from the beginning of the data, which is `0` in the above case. Can anyone please help on this issue? If the first output is also expected, how can I then enforce that every time the CSVIter is created, it resets to the beginning of the loaded data?

By the way, below is a screen shot of the above outputs:
![screenshot](https://cloud.githubusercontent.com/assets/185190/15584298/d76dda2e-232e-11e6-8b48-fb0975ca53cb.png)

Thanks.

**Comment by Gazillionth** [comment] 2016-05-26 17:33
I ran your code and most of the time I got your first output. However, once I got another variation on the output (below).

This is very strange. Whatever about starting at the first row of the CSV, surely the output of this code should be completely deterministic. This is potentially a serious bug, especially if two iterators can become misaligned. Can an MXNet developer shed any light here?

```
* batch 1: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 7.]
 [ 8.]
 [ 9.]]

* batch 2: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 10.]
 [  1.]
 [  2.]]

* batch 3: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 3.]
 [ 4.]
 [ 5.]]

* batch 4: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 6.]
 [ 7.]
 [ 8.]]

* batch 5: len(data[0]) = 3, b.pad = 1
data[0]:
[[  9.]
 [ 10.]
 [  1.]]
```

**Comment by EasonD3** [comment] 2016-05-31 18:47
@Gazillionth Thanks for helping confirm that. @mli @tqchen @antinucleon @piiswrong, can you please help take a look? If the issue indeed exists, it could badly affect the data alignment when `CSVIter` is to be merged with other iterators. Thank you.

**Comment by R1ncy** [comment] 2016-08-16 03:43
hi, i use the same code and data.csv as you. 
**But i can't get "1", it is changed to "0".** 
**i reset the iter everytime but it doesn't start from "1" or "0".**
**iter doesn't return with 10 nums sometime.**
does iter drop some nums?
how to fix it? thanks for your attention

here's my output:
>>> iter = mx.io.CSVIter(data_csv=r"C:\Users\Administrator.PC-20160614XTKQ\Desktop\data.csv",data_shape=(1,), batch_size=3)
>>> print_iter(iter)
* batch 1: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 3.]
 [ 4.]
 [ 5.]]

* batch 2: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 6.]
 [ 7.]
 [ 8.]]

* batch 3: len(data[0]) = 3, b.pad = 1
data[0]:
[[  9.]
 [ 10.]
 [  0.]]


>>> print_iter(iter)
* batch 1: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 2.]
 [ 3.]
 [ 4.]]

* batch 2: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 5.]
 [ 6.]
 [ 7.]]

* batch 3: len(data[0]) = 3, b.pad = 0
data[0]:
[[  8.]
 [  9.]
 [ 10.]]


>>> print_iter(iter)
* batch 1: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 0.]
 [ 2.]
 [ 3.]]

* batch 2: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 4.]
 [ 5.]
 [ 6.]]

* batch 3: len(data[0]) = 3, b.pad = 0
data[0]:
[[ 7.]
 [ 8.]
 [ 9.]]

* batch 4: len(data[0]) = 3, b.pad = 2
data[0]:
[[ 10.]
 [  0.]
 [  2.]]

**Comment by pluskid** [comment] 2016-08-16 21:47
I believe the OP's issue is due to threaded prefetching. The thread started prefetching once the data iter is created and then a `reset` call interrupted it. The "correct" way is to avoid calling `reset()` until a first round over the data iter is finished. For example, in the OP's test code, if the `reset()` call is moved to the end of `print_iter`, then you will see the expected behavior.

**Comment by R1ncy** [comment] 2016-08-17 01:00
@pluskid thanks for your reply. 
I moved the reset() to the end and here is the code:

def print_iter(iter):    
    inx = 1
    for b in iter:
        print(inx)
        data = b.data[0]
        label = b.label[0]
        print(data.asnumpy())
        print(label.asnumpy())
        inx +=1
    iter.reset()

my data is:
**1,1,1**
2,2,2
3,3,3
4,4,4
5,5,5
6,6,6
7,7,7
8,8,8
9,9,9
10,10,10

and label is:
1
2
3
4
5
6
7
8
9
10

Then I use this code to get the datasetiter:
eg = mx.io.CSVIter(data_csv=r"d:\data.csv",data_shape=(3,),batch_size=3,label_csv=r"d:\tag.csv",label_shape=(1,))
and run the code:
print_iter(eg)
it prints:
1
[**[ 0.  1.  1.]**
 [ 2.  2.  2.]
 [ 3.  3.  3.]]
[ 1.  2.  3.]
2
[[ 4.  4.  4.]
 [ 5.  5.  5.]
 [ 6.  6.  6.]]
[ 4.  5.  6.]
3
[[ 7.  7.  7.]
 [ 8.  8.  8.]
 [ 9.  9.  9.]]
[ 7.  8.  9.]
4
[[ 10.  10.  10.]
 **[  0.   1.   1.]**
 [  2.   2.   2.]]
[ 10.   1.   2.]

>>> print_iter(eg)
1
[[ 3.  3.  3.]
 [ 4.  4.  4.]
 [ 5.  5.  5.]]
[ 3.  4.  5.]
2
[[ 6.  6.  6.]
 [ 7.  7.  7.]
 [ 8.  8.  8.]]
[ 6.  7.  8.]
3
[[  9.   9.   9.]
 [ 10.  10.  10.]
 **[  0.   1.   1.]]**
[  9.  10.   1.]

1.the first line of data is "1,1,1", but func print_iter prints it as "0,1,1". Anything wrong with my code?
2.I moved the "reset()" to the end but it seems the same as at the start from the result.

**Comment by pluskid** [comment] 2016-08-17 03:45
Great! Closing for now. Feel free to re-open if needed.

**Closed by pluskid** 2016-08-17 03:45 UTC
