### ISSUE TITLE
How to build an MLP by MXNet?

### ISSUE THREAD

**Issue by were** [dmlc/mxnet#831] opened 2015-12-05 09:15 UTC
I try to use MXNet to build an MLP for interpolation.

Here is my python code, to use this code, `python build.py 5 5 8 8 8 2`.

It tries to build a 5-layer MLP, which treats a 5-d vector as input and a 2-d vector as output.

There are 3 hidden layers for this MLP, each layer has 8 neurons.

`````
import mxnet as mx
import numpy
import sys

#print sys.argv
args = sys.argv[1:]
try:
    print args
    n_layers = int(args[0])
except:
    print 'The first argument should be number of layers!'
    quit()

nn = None
try:
    nn = mx.symbol.Variable('data')
    print 'shape is', nn.infer_shape
except:
    print 'Failed to initialize input layer!'
    quit()

try:
    for i in range(2, n_layers):
        nn = mx.symbol.FullyConnected(data = nn, name = 'hidden-recept-' + str(i), num_hidden = int(args[i]))
        nn = mx.symbol.Activation(data = nn, name = 'hidden-act-' + str(i), act_type = 'relu')
except:
    print 'Failed to initailize hidden layer!'
    quit()

try:
    nn = mx.symbol.FullyConnected(data = nn, name = 'hidden-recept-' + str(n_layers), num_hidden = int(args[n_layers]))
    nn = mx.symbol.LinearRegressionOutput(data = nn, name = 'softmax')
except:
    print 'Failed to build output layer!'
    quit()

data = open('data').readlines()
x,y = [],[]
for i in xrange(len(data)):
    if i % 2 == 0:
        x.append(map(float, data[i].split()))
    else:
        y.append(map(float, data[i].split()))
x = mx.ndarray.array(x).asnumpy()
y = mx.ndarray.array(y).asnumpy()
iterator = mx.io.NDArrayIter(data = x, label = y, batch_size = 128)
#print iterator.provide_data, iterator.provide_label

data = open('test').readlines()
x,y = [],[]
for i in xrange(len(data)):
    if i % 2 == 0:
        x.append(map(float, data[i].split()))
    else:
        y.append(map(float, data[i].split()))
x = mx.ndarray.array(x).asnumpy()
y = mx.ndarray.array(y).asnumpy()
tester = mx.io.NDArrayIter(data = x, label = y, batch_size = 128)
#print provide_data, provide_label

model = mx.model.FeedForward(
        symbol = nn,
        ctx = mx.gpu(0),
        num_epoch = 1000,
        learning_rate = .1,
        momentum = .9,
        wd = 1e-5,
        initializer = mx.init.Xavier(factor_type = 'in', magnitude = 2.34)
)

print iterator.provide_data, iterator.provide_label
model.fit(
        X = iterator,
        eval_data = tester,
        batch_end_callback = mx.callback.Speedometer(128, 50)
)

model.save("res")
tester.next()
print model.predict(tester)
`````

If I use `eval_data`, it gives me the following error log:

`````
Traceback (most recent call last):
  File "builder.py", line 79, in <module>
    tester.next()
  File "/Users/were/Lab/nnbuilder/mxnet/io.py", line 213, in next
    raise StopIteration
StopIteration
`````

**Comment by piiswrong** [comment] 2015-12-05 09:18
tester is an iterator. I has reached the end so calling next() will give StopIteration exception:
https://docs.python.org/2/library/exceptions.html#exceptions.StopIteration
Just remove that line and your code should work fine.

**Comment by were** [comment] 2015-12-05 09:49
Could you please give me more help about building an MLP?

**Comment by piiswrong** [comment] 2015-12-05 10:01
You can have a look at the examples. Like example/numpy-howto/numpysoftmax.py and image-classification/train mnist

**Comment by were** [comment] 2015-12-05 10:06
Yeah, in fact, I did, but it helps little.
What I want to do is simpler than image classification(I think).
I just want to handle some vectors on real-number field.

Besides, my code starts to work now, I imitate the usage of `batch_end_callback` in `train_model.py`.
I used `mx.callback.Speedometer`, but it gives me nothing about speed and accuracy.

**Comment by piiswrong** [comment] 2015-12-05 10:09
You need to import logging and set it's level to debug. 

This seems to be a gotcha. @tqchen maybe we should change it.

**Comment by were** [comment] 2015-12-05 10:21
Hmmmm, OK... I used `logging` which enables the `INFO`.
But the validation accuracy of my model is alway zero...

Any ideas?

**Comment by were** [comment] 2015-12-05 11:08
Or what I want to ask is how to set up a `DataIter`.
I used `NDArrayIter`. What should the inside data look like in the corresponding `NDArray`?

**Comment by piiswrong** [comment] 2015-12-05 20:18
NDArrayIter takes a bunch of numpy arrays and wrap them as a data iterator.

**Comment by piiswrong** [comment] 2015-12-05 20:21
you can create a monitor with mon = mx.monitor.Monitor(1) and add monitor=mon to model.fit to see what's going on in side the model.

**Comment by were** [comment] 2015-12-06 05:55
What I want to know is the layout of the data in an `NDArray`.
For example, I want the MLP to process on vectors.
I build up a 2-d `NDArray`
``````
[[1 2 3 4 5]
 [1 2 3 4 5]
 ...
 [1 2 3 4 5]]
``````
Each `[1 2 3 4 5]` is an input vector.
Is the usage right?

**Comment by piiswrong** [comment] 2015-12-06 05:58
yes

**Comment by were** [comment] 2015-12-06 06:06
What should `eval_data` in `fit` looks like?
Be a tuple of two `NDArray`s?

In my comprehension, `eval_data` is used for evaluating the result of fitting, isn't it?

**Comment by piiswrong** [comment] 2015-12-06 06:07
both training and eval data are DataIters

**Comment by were** [comment] 2015-12-06 06:16
Besides, if I give my model a `DataIter` to predict, all of the results are the same.

**Comment by were** [comment] 2015-12-06 06:16
I used 'monitor' to watch the training procedure.
It does adapting the weight on the neurons, but the accuracy is always 0.

**Comment by were** [comment] 2015-12-06 06:17
How is the accuracy estimated?

**Comment by were** [comment] 2015-12-06 15:52
I want the error rate is MSE (mean square error), rather than accuracy of predicting.

**Comment by piiswrong** [comment] 2015-12-06 21:29
you can create your own metric with mx.metric.CustomMetric

**Comment by were** [comment] 2015-12-07 05:06
OK... I will learn about it later.

**Comment by were** [comment] 2015-12-07 12:24
I used `CustomMetric` it works well.
However, I am suffering from another problem now.

It works well on the vector whose dimension is greater than one.
If the output vector is 1-d vector, the MXNet will raise shape not match exception.

**Comment by were** [comment] 2015-12-07 12:56
There's another thing I want to know.
The default configuration of a model is to maximize the value given by metric.
How can I set it to minimize, in some condition I can only estimate the error rather than accuracy?

**Comment by tqchen** [comment] 2015-12-09 16:18
The metric is only used to show evalaution statistics, with nothing related to the objective function. The objective is defined by what Output node you used in the graph, such as SoftmaxOutput and RegressionOutput

**Comment by were** [comment] 2015-12-11 08:36
OK, I have got wrong with the function of metric.
I thought it is response to both evaluation and objective.

**Comment by were** [comment] 2015-12-11 08:43
Another problem is that I faced a problem when the output vector is 1d.
It raises error.

**Comment by tqchen** [comment] 2015-12-11 15:13
@were I am going to close this issue for now. Can you open another issue with a small snippet that reproduces your problem? We can take a look. The accuracy measure was only defined for more probability output of each class, so not 1d vector

**Closed by tqchen** 2015-12-11 15:13 UTC

**Comment by were** [comment] 2015-12-11 18:10
OK, let me reproduce my problem.

Thank you for helping me a lot.
