### ISSUE TITLE
Can mxnet share GPU memory across all buckets?

### ISSUE THREAD

**Issue by GrindstoneLZX** [dmlc/mxnet#1799] opened 2016-04-06 15:18 UTC
I have implemented LSTM layer for speech task with utterance parallelization, and I use bucketing to deal with variable-length inputs. However, I notice that GPU memory usage will increase when I raise bucket number. So I think mxnet will allocate GPU memory for every bucket. Is it possible for mxnet to share GPU memory across all buckets?
This is the GPU memory usage vs. bucket number and parallel utterance number

GPU memory (MB)   |  parallel_num = 25    |	parallel_num = 40	  |   parallel_num = 60
----------------------------|-----------------------------|------------------------------|----------------------------
bucket_num = 10	  |  3751	                     |   6016	                  |   8120
bucket_num = 20	  |  4391	                     |   7085	                  |   9810
bucket_num = 50	  |  6576	                      |  10549	                  |
bucket_num = 70	 |   8058		             |                                   |
bucket_num = 100	  |  10021		             |                                    |

**Comment by GrindstoneLZX** [comment] 2016-04-06 15:26
![memory usage](https://cloud.githubusercontent.com/assets/18130064/14322317/f385cc32-fc4e-11e5-9924-b35917539dfb.png)

**Comment by pluskid** [comment] 2016-04-06 15:35
@GrindstoneLZX The memory should already been shared across buckets -- essentially, the total memory consumption should be equal to the largest bucket (e.g. the longest sequence). Can you try to set the longest sequence to be of the same length in all the cases to see if the memory still grows noticeably with the number of buckets?

**Comment by pluskid** [comment] 2016-04-06 15:36
BTW: that mechanism are you using the measure the device memory? We are also interested in doing some more test on the memory consumption, but did not get good way to measure the device memory usage yet.

**Comment by GrindstoneLZX** [comment] 2016-04-07 03:56
thank you @pluskid for your reply!
I use Tesla K40 for my experiments and I measure GPU memory usage by simply using 'nvidia-smi' to observe the maximum usage during training.
In all caces I use the same dataset. My dataset is a speech dataset with 4620 utterances, and the frame number (sequence length) of each utterance ranges from 54 to 487. I set buckets in a way that the number of utterances is roughly equal in each bucket. For example:

bucket[0]|bucket[1]|bucket[2]|...|bucket[N-2]|bucket[N-1]
----|-----|-----|---|----|------
89|126|178|...|321|487 

the default_bucket_key of my DataIter is **bucket[0]**. During training, first I select one bucket and then select several utterances as one mini-batch. If the mini-batch is not full, I will fill it with zeros. I have tried two different way to select buckets. 
The result I reported yesterday is the selecting buckets in an ascending order, which is **89, 126, 178, ... , 321, 487**. 

And I also tried descending order, which is **487, 321, ..., 178, 126, 89**. The result is:

GPU memory (MB)   |  parallel_num = 25    |	parallel_num = 40	  |   parallel_num = 60
----------------------------|-----------------------------|------------------------------|----------------------------
bucket_num = 10	  |  3321	                     |   5454	                  |   7080
bucket_num = 20	  |  3638	                     |   5945	                  |   7846
bucket_num = 50	  |  3568	                      |  5881	                  |   7699
bucket_num = 70	 |   3553		             |    5774                         |  7658
bucket_num = 100	  |  3537		             |   5728                          |   7626

![memory usage 2](https://cloud.githubusercontent.com/assets/18130064/14339296/1e6d7b28-fcb0-11e5-963c-a622726b6367.png)

And I also tried random order, the memory usage is random too. 

I tried to set default_bucket_key to buckets[N-1] to pre-allocate maximum memory space, but when I set default_bucket_key = buckets[N-1], I get an error:

2016-04-07 11:49:12,823 Start training with [gpu(0)]
[11:49:13] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:49:13] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:49:13] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:49:13] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:49:13] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:49:13] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
bucket: 216
[11:49:20] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:49:20] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:49:20] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:49:20] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:49:20] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:49:20] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
Traceback (most recent call last):
  File "TrainSchedule2.py", line 162, in <module>
    epoch_end_callback=mx.callback.do_checkpoint(save_prefix),)
  File "/home/zxlee/Downloads/miniconda2/envs/mxnet2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 770, in fit
    sym_gen=self.sym_gen)
  File "/home/zxlee/Downloads/miniconda2/envs/mxnet2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 221, in _train_multi_device
    executor_manager.load_data_batch(data_batch)
  File "/home/zxlee/Downloads/miniconda2/envs/mxnet2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 374, in load_data_batch
    shared_group=self.execgrp)
  File "/home/zxlee/Downloads/miniconda2/envs/mxnet2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 221, in __init__
    for i in self.param_idx]
IndexError: list index out of range

Do you have any ideas?

**Comment by pluskid** [comment] 2016-04-09 20:42
@GrindstoneLZX sorry I don't quite understand what your figure mean. Setting default bucket to be the largest one might be a good way to try. Please remember when you set the default bucket, the `provide_data` and `provide_label` on the DataIter should match that of the default bucket. Can you double check that? Thanks!

**Comment by piiswrong** [comment] 2016-04-09 23:29
Your figure looks reasonable to me.
The error seems strange. Could you give a minimal script that reproduce this error?

**Comment by GrindstoneLZX** [comment] 2016-04-12 14:22
@piiswrong @pluskid 
I wrote a simple LSTM implementation script:

- The LSTM layer module is `lstm_layer`, and 'lstm_layer_init_states()' is a function to get `init_states` for data iterator.

- The DataIter `simple_data_iterator` generates data and labels: `label = np.ones` and `data = label + np.random.normal`.
 - `fea_len` is the feature length, `bucket_num` is the bucket number, `batch_size` is the utterance parallel number, `max_seq_len` is the maximum sequence length of all utterances.
 - `order` controls the way `simple_data_iterator` selects bucket when called `next()`: 
  - When `order = 'ascend'`, `bucket_key` is set **from 1 to `max_seq_len`**,
  - When `order = 'descend'`, `bucket_key` is set from **`max_seq_len` to 1**, 
  - When `order = random`, `bucket_key` is set in random order. 
 - `simple_data_iterator.next()` changes bucket_key according to `order` and returns one `simple_batch` each time. 

- I built a 3 LSTM layers network, each LSTM layer has 256 hidden nodes, I change `max_seq_len`, `bucket_num` and `order` in experiments.

- Here is my script:

```python
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 12 17:32:32 2016

@author: zxlee
"""
import mxnet as mx
import numpy as np
from collections import namedtuple

LSTMState = namedtuple("LSTMState", ["c", "h"])
LSTMParam = namedtuple("LSTMParam", ["i2h_weight", "i2h_bias",
                                     "h2h_weight", "h2h_bias"])

''' one lstm cell '''                                     
def lstm_cell(indata, prev_state, param, num_hidden, cell_idx, layer_name, dropout=0.):
    if dropout > 0.:
        indata = mx.sym.Dropout(data=indata, p=dropout)
    i2h = mx.sym.FullyConnected(data=indata,
                                weight=param.i2h_weight,
                                bias=param.i2h_bias,
                                num_hidden=num_hidden * 4,
                                name="%s_t%d_i2h" % (layer_name, cell_idx))
    h2h = mx.sym.FullyConnected(data=prev_state.h,
                            weight=param.h2h_weight,
                            bias=param.h2h_bias,
                            num_hidden=num_hidden * 4,
                            name="%s_t%d_h2h" % (layer_name, cell_idx))
    gates = i2h + h2h
    
    slice_gates = mx.sym.SliceChannel(gates, num_outputs=4,
                                      name="%s_t%d_slice" % (layer_name, cell_idx))
    in_gate = mx.sym.Activation(slice_gates[0], act_type="sigmoid")
    in_transform = mx.sym.Activation(slice_gates[1], act_type="tanh")
    forget_gate = mx.sym.Activation(slice_gates[2], act_type="sigmoid")
    out_gate = mx.sym.Activation(slice_gates[3], act_type="sigmoid")
    next_c = (forget_gate * prev_state.c) + (in_gate * in_transform)
    next_h = out_gate * mx.sym.Activation(next_c, act_type="tanh")
    return LSTMState(c=next_c, h=next_h)

''' one layer lstm '''    
def lstm_layer(inputs, num_hidden, name, dropout=0.):
    
    layer_param = LSTMParam(i2h_weight=mx.sym.Variable("%s_i2h_weight" % name),
                            i2h_bias=mx.sym.Variable("%s_i2h_bias" % name),
                            h2h_weight=mx.sym.Variable("%s_h2h_weight" % name),
                            h2h_bias=mx.sym.Variable("%s_h2h_bias" % name))
                                             
    prev_state = LSTMState(c=mx.sym.Variable("%s_init_c" % name),
                           h=mx.sym.Variable("%s_init_h" % name))                            
                                
    layer_out = []
    for i in range(len(inputs)):
        next_state = lstm_cell(inputs[i], prev_state, layer_param, num_hidden, i, name, dropout)
        prev_state = next_state
        layer_out.append(next_state.h)
        
    return layer_out

''' lstm init_states for data iterator '''
def lstm_layer_init_states(batch_size, num_hidden, name):
    init_c = ('%s_init_c'%name, (batch_size, num_hidden))
    init_h = ('%s_init_h'%name, (batch_size, num_hidden))
    return [init_c, init_h]
    
''' mxnet interface batch '''
class simple_batch(object):
    def __init__(self, data_names, data, label_names, label, bucket_key):
        self.data = data
        self.label = label
        self.data_names = data_names
        self.label_names = label_names
        self.bucket_key = bucket_key
        
    @property
    def provide_data(self):
        return [(n, x.shape) for n, x in zip(self.data_names, self.data)]
        
    @property
    def provide_label(self):
        return [(n, x.shape) for n, x in zip(self.label_names, self.label)]
        
class simple_data_iterator(mx.io.DataIter):
    def __init__(self, init_states, data_name='data', label_name='label',
                 fea_len=257, bucket_num=10, batch_size=10, order='ascend', max_seq_len=500):
        
        self.init_states = init_states
        self.data_name = data_name
        self.label_name = label_name
        self.fea_len = fea_len
        self.bucket_num = bucket_num
        self.batch_size = batch_size
        self.order = order
        self.max_seq_len = max_seq_len
        
        ''' for buckets '''
        self.buckets = np.linspace(1, max_seq_len, num=bucket_num, dtype='int32')
        self.bucket_indices = np.arange(len(self.buckets))
        if order is 'descend':
            self.bucket_indices = self.bucket_indices[::-1]
        
        ''' for mxnet interface '''
        self.init_states = init_states
        self.init_state_arrays = [mx.nd.zeros(x[1]) for x in init_states]
        self.init_state_names = [x[0] for x in self.init_states]
        self.default_bucket_key = self.buckets[0]
        self.provide_data = [('%s_t%d' % (self.data_name, t), (batch_size, fea_len))
                             for t in range(self.default_bucket_key)] + init_states
        self.provide_label = [('%s_t%d' % (self.label_name, t), (batch_size, fea_len))
                              for t in range(self.default_bucket_key)]
    
        ''' for next() '''
        self.bucket_load_idx = 0
        
    def reset(self):
        if self.order is 'random':
            np.random.shuffle(self.bucket_indices)
        self.bucket_load_idx = 0
                    
    def next(self):
        if self.bucket_load_idx >= len(self.bucket_indices):
            raise StopIteration
        else:
            bucket_key = self.buckets[self.bucket_indices[self.bucket_load_idx]]
            print bucket_key
            random_label = np.ones((bucket_key, self.batch_size*self.fea_len), dtype='float32')            
            random_data = random_label + np.random.normal(size=((bucket_key, self.batch_size*self.fea_len)))
            
            data_all = [mx.nd.array(random_data[t,:].reshape((self.batch_size, self.fea_len))) \
                        for t in range(bucket_key)] + self.init_state_arrays
            label_all = [mx.nd.array(random_label[t,:].reshape((self.batch_size, self.fea_len))) \
                        for t in range(bucket_key)]
            data_names = ['%s_t%d' % (self.data_name, t) for t in range(bucket_key)] + self.init_state_names
            label_names = ['%s_t%d' % (self.label_name, t) for t in range(bucket_key)]
            
            batch = simple_batch(data_names, data_all, label_names, label_all, bucket_key)
            
            self.bucket_load_idx += 1
            return batch
            
    def __next__(self):
        return self.next(self)
        
    def __iter__(self):
        return self
        
        
if __name__ == '__main__':
    gpus = [0]
    batch_size = 30
    
    # set bucket order: can be set to 'ascend', 'descend', 'random'
    order = 'descend'
    bucket_num = 40
    max_seq_len = 240
    do_val = False
    
    learning_rate = 0.001
    momentum = 0.9
    weight_decay = 0.00001
    
    num_epoch = 30
    
    fea_len = 257
    input_name = 'data'
    label_name = 'label'

    ''' define network: sym_gen and get_init_states '''
    num_hidden1 = 256
    num_hidden2 = 256
    num_hidden3 = 256
    
    def sym_gen(seq_len):
        reg_weight = mx.sym.Variable('reg_weight')
        reg_bias = mx.sym.Variable('reg_bias')        
        input_sym = [mx.sym.Variable('%s_t%d' % (input_name, t)) for t in range(seq_len)]
        label_sym = [mx.sym.Variable('%s_t%d' % (label_name, t)) for t in range(seq_len)]        
        label_concat = mx.sym.Concat(*label_sym, dim=0, name='label_concat')
        
        lstm1 = lstm_layer(input_sym, num_hidden1, 'lstm1')
        lstm2 = lstm_layer(lstm1, num_hidden2, 'lstm2')
        lstm3 = lstm_layer(lstm2, num_hidden3, 'lstm3')
        
        lstm_out_concat = mx.sym.Concat(*lstm3, dim=0, name='lstm_out_concat')
        fc = mx.sym.FullyConnected(data=lstm_out_concat, 
                                   weight=reg_weight, 
                                   bias=reg_bias, 
                                   num_hidden=fea_len,
                                   name='fc')
        reg_all = mx.sym.LinearRegressionOutput(data=fc, label=label_concat, name='reg_all')
        reg_slice = mx.sym.SliceChannel(reg_all, num_outputs=seq_len, axis=0, name='reg_slice')
        return reg_slice
    
    def get_init_states():
        lstm1_init_states = lstm_layer_init_states(batch_size, num_hidden1, 'lstm1')
        lstm2_init_states = lstm_layer_init_states(batch_size, num_hidden2, 'lstm2')
        lstm3_init_states = lstm_layer_init_states(batch_size, num_hidden3, 'lstm3')
        return lstm1_init_states + lstm2_init_states + lstm3_init_states
            
    symbol = sym_gen
    init_states = get_init_states()

    ''' prepare data '''
    train_iterator = simple_data_iterator(init_states,
                                          fea_len=fea_len,
                                          bucket_num=bucket_num, 
                                          batch_size=batch_size,
                                          max_seq_len=max_seq_len,
                                          order=order)
    if do_val:                                      
        val_iterator = simple_data_iterator(init_states,
                                            fea_len=fea_len,
                                            bucket_num=bucket_num, 
                                            batch_size=batch_size,
                                            max_seq_len=max_seq_len,
                                            order=order)
    else:
        val_iterator = None                                        
                                        
    ''' training '''
    contexts = [mx.context.gpu(i) for i in gpus]
    
    optimizer = mx.optimizer.SGD(learning_rate=learning_rate,
                                 momentum=momentum,
                                 wd=weight_decay,
                                 clip_gradient=1) 

    initializer = mx.initializer.Xavier(factor_type='in',magnitude=3)
                                        
    model = mx.model.FeedForward(symbol=symbol, 
                                 ctx=contexts,
                                 num_epoch=num_epoch,
                                 optimizer=optimizer,
                                 initializer=initializer)

    import logging
    head = '%(asctime)-15s %(message)s'
    logging.basicConfig(level=logging.DEBUG, format=head)

    model.fit(X=train_iterator, eval_data=val_iterator, eval_metric='mse',
              batch_end_callback = mx.callback.Speedometer(batch_size, 1)) 
```


- The memory usage results are:

max_seq_len=120 | order=descend | order=ascend
-------------------------|--------------|----------
bucket_num=20    | 395          |461
bucket_num=40    | 395          |597
bucket_num=60    | 395          |720

max_seq_len=240 |order=descend | order=ascend
-------------------------|--------------|----------
bucket_num=20    | 575          |723
bucket_num=40    | 608          |1053
bucket_num=60    | 596          |1320

max_seq_len=360 | order=descend | order=ascend
-------------------------|--------------|----------
bucket_num=20    | 790          |1011
bucket_num=40    | 790          |1468
bucket_num=60    | 823          |1917

- here is the figure:

`order = descend`:
![descend](https://cloud.githubusercontent.com/assets/18130064/14462577/4f3a4774-00fa-11e6-82f7-fa52bab3e2b6.png)

`order = ascend`:
![ascend](https://cloud.githubusercontent.com/assets/18130064/14462579/56a29b1a-00fa-11e6-8801-0e983b8b0636.png)

- It seems that when `order = ascend`, memory usage increases at python/executor_manager.py in `_bind_exec()` at this line:
```python
executor = sym.bind(ctx=ctx, args=arg_arrays, args_grad=grad_arrays,
                        aux_states=aux_arrays,
                        grad_req=grad_req, shared_exec=base_exec)
```

**Comment by pluskid** [comment] 2016-04-12 15:10
@GrindstoneLZX Thanks for the detailed test case. After inserting some print statements into `_bind_exec()` as

```patch
diff --git a/python/mxnet/executor_manager.py b/python/mxnet/executor_manager.py
index 6f5fcfd..628f0aa 100644
--- a/python/mxnet/executor_manager.py
+++ b/python/mxnet/executor_manager.py
@@ -115,7 +115,7 @@ def _bind_exec(sym, ctx, input_shapes, param_names, need_grad=False,
         raise AssertionError("need_grad must be boolean or set.")
     grad_req = {name:('write' if name in need_grad else 'null') for name in arg_names}

-
+    print('############ _bind_exec on %s' % ctx)
     # create or borrow arguments and gradients
     for i in range(len(arg_names)):
         name = arg_names[i]
@@ -124,12 +124,14 @@ def _bind_exec(sym, ctx, input_shapes, param_names, need_grad=False,
             if shared_data_arrays is not None and \
                     name in shared_data_arrays:
                 arg_arr = shared_data_arrays[name]
+                print('@@@ reusing %s...' % name)

                 # in bucketing, we want to be strict here to avoid
                 # potential bugs
                 assert(arg_shape[i] == arg_arr.shape)
                 assert(arg_types[i] == arg_arr.dtype)
             else:
+                print('### allocating %s...' % name)
                 arg_arr = nd.zeros(arg_shape[i], ctx, dtype=arg_types[i])
             arg_arrays.append(arg_arr)
             if shared_data_arrays is not None:
@@ -137,11 +139,13 @@ def _bind_exec(sym, ctx, input_shapes, param_names, need_grad=False,
         else:
             # model parameter
             if base_exec is None:
+                print('### allocating %s...' % name)
                 arg_arr = nd.zeros(arg_shape[i], ctx, dtype=arg_types[i])
                 if name in need_grad:
                     grad_arr = nd.zeros(arg_shape[i], ctx, dtype=arg_types[i])
                     grad_arrays[name] = grad_arr
             else:
+                print('@@@ reusing %s...' % name)
                 arg_arr = base_exec.arg_dict[name]
                 assert arg_arr.shape == arg_shape[i]
                 assert arg_arr.dtype == arg_types[i]
```
I can see that the memory sharing works as expected -- only the extra data and label blocks are allocated each time bucket length is increased. 
```
...
2016-04-12 11:02:41,455 Epoch[0] Batch [2]      Speed: 650.74 samples/sec       Train-mse=1.004897
13
############ _bind_exec on gpu(0)
@@@ reusing data_t0...
@@@ reusing lstm1_i2h_weight...
@@@ reusing lstm1_i2h_bias...
@@@ reusing lstm1_init_h...
@@@ reusing lstm1_h2h_weight...
@@@ reusing lstm1_h2h_bias...
@@@ reusing lstm1_init_c...
@@@ reusing lstm2_i2h_weight...
@@@ reusing lstm2_i2h_bias...
@@@ reusing lstm2_init_h...
@@@ reusing lstm2_h2h_weight...
@@@ reusing lstm2_h2h_bias...
@@@ reusing lstm2_init_c...
@@@ reusing lstm3_i2h_weight...
@@@ reusing lstm3_i2h_bias...
@@@ reusing lstm3_init_h...
@@@ reusing lstm3_h2h_weight...
@@@ reusing lstm3_h2h_bias...
@@@ reusing lstm3_init_c...
@@@ reusing data_t1...
@@@ reusing data_t2...
@@@ reusing data_t3...
@@@ reusing data_t4...
@@@ reusing data_t5...
@@@ reusing data_t6...
### allocating data_t7...
### allocating data_t8...
### allocating data_t9...
### allocating data_t10...
### allocating data_t11...
### allocating data_t12...
@@@ reusing reg_weight...
@@@ reusing reg_bias...
@@@ reusing label_t0...
@@@ reusing label_t1...
@@@ reusing label_t2...
@@@ reusing label_t3...
@@@ reusing label_t4...
@@@ reusing label_t5...
@@@ reusing label_t6...
### allocating label_t7...
### allocating label_t8...
### allocating label_t9...
### allocating label_t10...
### allocating label_t11...
### allocating label_t12...
...
```

My best guess is that nvidia-smi is not very accurate at counting memory when you increasingly allocate a bunch of relative small memory blocks. Or @tqchen @antinucleon do we have a customized memory allocator for `NDArray` that might not be very optimized under this situation?

**Comment by tqchen** [comment] 2016-04-12 16:19
In current implementation, the memory will always be reused from the executor binded from default key. We need to make sure that the default key uses the maximum length. Otherwise the other executors will grab more memory

**Comment by tqchen** [comment] 2016-05-07 04:16
@pluskid @piiswrong 

I rethinked about this issue, it was due to the fact the input arguments(data of different timestamps)(which are binded) is not shared across buckets because they are not allocated by the executor, instead passed in by outside, thus was not shard.

**Comment by piiswrong** [comment] 2016-05-07 04:24
@tqchen They can still be shared, but the front end need to handle it. executor.reshape does this

**Comment by pluskid** [comment] 2016-05-07 14:08
Yes, bucketing also tries to share the inputs. 

1. If it is the inputs with the same name and same shape, they are just shared.
2. If it is the inputs with the same name but smaller shape, then a subset of the existing array is used for sharing. (This is why we now encourage to set the `default_bucket_key` to correspond to the largest bucket.

**Comment by tqchen** [comment] 2016-05-07 16:14
I see, so I guess if user set default to largest key, this problem is kinda of already resolved? if so I will close this issue

**Comment by pluskid** [comment] 2016-10-19 14:32
Closing due to inactivity.

**Closed by pluskid** 2016-10-19 14:32 UTC
