### ISSUE TITLE
invalid pointer error while using reshape

### ISSUE THREAD

**Issue by ascust** [dmlc/mxnet#1474] opened 2016-02-15 05:39 UTC
I tried to use reshape of a executor. If the executor is defined in cpu, it was fine. But when I tried to use it in gpu mode, I got this error:
```
Error in 'python' : munmap_chunk(): invalid pointer: 0x00000001042adb4
Aborted (core dumped)
```
any idea how this happened? Thanks a lot

**Comment by piiswrong** [comment] 2016-02-15 07:17
Could you provide a script that reproduce this error? It's hard to figure out what exactly you have done.

**Comment by horserma** [comment] 2016-02-15 23:43
```
ctx = mx.gpu(0)
data = mx.symbol.Variable("data")
net = mx.symbol.Convolution(data=data, kernel=(3,3), num_filter=64)
net = mx.symbol.Activation(data=net, act_type="relu")
net = mx.symbol.Convolution(data=net,kernel=(3,3), num_filter=64)
net = mx.symbol.Activation(data=net, act_type="relu")
net = mx.symbol.Pooling(data=net, pool_type="max", kernel=(2,2))
executor = net.simple_bind(ctx=ctx,data=(1,3,512,512),grad_req="null")
executor = executor.reshape(allow_up_sizing=True, data = (1,3,400,600))
executor.forward(is_train=False)
```
you can try this. The error is kind of unpredictable. Sometimes, it happens. Most of the time, I would get a segmentation fault error. If I dont use reshape, nothing would ever happen. As long as I use this function, either I get a segmentation fault or a pointer error. Please check it out.

**Comment by ascust** [comment] 2016-02-15 23:44
```
ctx = mx.gpu(0)
data = mx.symbol.Variable("data")
net = mx.symbol.Convolution(data=data, kernel=(3,3), num_filter=64)
net = mx.symbol.Activation(data=net, act_type="relu")
net = mx.symbol.Convolution(data=net,kernel=(3,3), num_filter=64)
net = mx.symbol.Activation(data=net, act_type="relu")
net = mx.symbol.Pooling(data=net, pool_type="max", kernel=(2,2))
executor = net.simple_bind(ctx=ctx,data=(1,3,512,512),grad_req="null")
executor = executor.reshape(allow_up_sizing=True, data = (1,3,400,600))
executor.forward(is_train=False)
```
you can try this. The error is kind of unpredictable. Sometimes, it happens. Most of the time, I would get a segmentation fault error. If I dont use reshape, nothing would ever happen. As long as I use this function, either I get a segmentation fault or a pointer error. Please check it out.

**Comment by ascust** [comment] 2016-02-15 23:46
@piiswrong

**Comment by piiswrong** [comment] 2016-02-16 00:02
This is caused by destruction of the first executor. Not reshape. The crash point is in cudnnDestroyTensorDescriptor in cudnn_activation-inl.h

I'm looking into it.

**Comment by piiswrong** [comment] 2016-02-16 00:30
@ascust Should be fixed once https://github.com/dmlc/mxnet/pull/1481 is merged.

**Closed** 2016-02-16 05:13 UTC
