### ISSUE TITLE
excample exception

### ISSUE THREAD

**Issue by junranhe** [dmlc/mxnet#111] opened 2015-09-21 09:28 UTC
when I update the code in afternoon,and run excample cifar10.py:
src/io/./image_augmenter.h:307: Check failed: p_data->size(1) >= param_.data_shape1] && p_data->size(2) >= param_.data_shape[2] Data size must be bigger than the input size to net

**Comment by antinucleon** [comment] 2015-09-22 01:16
Now fixed

**Comment by junranhe** [comment] 2015-09-22 02:29
when I update all the code, and run cifar10.py a few minute: the program is shuttdown
./mshadow/mshadow/./stream_gpu-inl.h:46: Check failed: (err) == (cudaSuccess) driver shutting down

**Comment by antinucleon** [comment] 2015-09-22 02:59
Please pull newest version and try again. We don't release formally yet, MXNet is still under heavily construction. I just checked on my machine for 10 epoch without any error.
```
INFO:root:Start training with 1 devices
Start training with 1 devices
INFO:root:Iteration[0] Train-accuracy=0.517203
Iteration[0] Train-accuracy=0.517203
INFO:root:Iteration[0] Time cost=46.501
Iteration[0] Time cost=46.501
INFO:root:Iteration[0] Validation-accuracy=0.654371
Iteration[0] Validation-accuracy=0.654371
INFO:root:Iteration[1] Train-accuracy=0.682545
Iteration[1] Train-accuracy=0.682545
INFO:root:Iteration[1] Time cost=49.707
Iteration[1] Time cost=49.707
INFO:root:Iteration[1] Validation-accuracy=0.717448
Iteration[1] Validation-accuracy=0.717448
INFO:root:Iteration[2] Train-accuracy=0.750341
Iteration[2] Train-accuracy=0.750341
INFO:root:Iteration[2] Time cost=51.103
Iteration[2] Time cost=51.103
INFO:root:Iteration[2] Validation-accuracy=0.770333
Iteration[2] Validation-accuracy=0.770333
INFO:root:Iteration[3] Train-accuracy=0.786345
Iteration[3] Train-accuracy=0.786345
INFO:root:Iteration[3] Time cost=51.618
Iteration[3] Time cost=51.618
INFO:root:Iteration[3] Validation-accuracy=0.799880
Iteration[3] Validation-accuracy=0.799880
INFO:root:Iteration[4] Train-accuracy=0.814378
Iteration[4] Train-accuracy=0.814378
INFO:root:Iteration[4] Time cost=51.882
Iteration[4] Time cost=51.882
INFO:root:Iteration[4] Validation-accuracy=0.818710
Iteration[4] Validation-accuracy=0.818710
INFO:root:Iteration[5] Train-accuracy=0.834014
Iteration[5] Train-accuracy=0.834014
INFO:root:Iteration[5] Time cost=51.480
Iteration[5] Time cost=51.480
INFO:root:Iteration[5] Validation-accuracy=0.828025
Iteration[5] Validation-accuracy=0.828025
INFO:root:Iteration[6] Train-accuracy=0.846108
Iteration[6] Train-accuracy=0.846108
INFO:root:Iteration[6] Time cost=51.643
Iteration[6] Time cost=51.643
INFO:root:Iteration[6] Validation-accuracy=0.836038
Iteration[6] Validation-accuracy=0.836038
INFO:root:Iteration[7] Train-accuracy=0.858754
Iteration[7] Train-accuracy=0.858754
INFO:root:Iteration[7] Time cost=51.551
Iteration[7] Time cost=51.551
INFO:root:Iteration[7] Validation-accuracy=0.834936
Iteration[7] Validation-accuracy=0.834936
INFO:root:Iteration[8] Train-accuracy=0.868706
Iteration[8] Train-accuracy=0.868706
INFO:root:Iteration[8] Time cost=51.658
Iteration[8] Time cost=51.658
INFO:root:Iteration[8] Validation-accuracy=0.843651
Iteration[8] Validation-accuracy=0.843651
INFO:root:Iteration[9] Train-accuracy=0.880535
Iteration[9] Train-accuracy=0.880535
INFO:root:Iteration[9] Time cost=51.401
Iteration[9] Time cost=51.401
INFO:root:Iteration[9] Validation-accuracy=0.848257
Iteration[9] Validation-accuracy=0.848257
```

**Comment by mli** [comment] 2015-09-22 03:00
it's a known bug, it happens when the static cuda is deleted earlier than the static engine. hopefully tianqi will fix it today

**Comment by antinucleon** [comment] 2015-09-22 03:02
I think Tianqi fixed it already

**Comment by mli** [comment] 2015-09-22 03:03
partially, there are still some corner cases

**Comment by junranhe** [comment] 2015-09-22 03:07
I try to update the code and submodule again but there is nothing to update...

**Comment by tqchen** [comment] 2015-09-22 04:15
Just pushed a fix to the master. Can you try again? Thanks alot for being early birds :) We know it is a bit harsh conditions in the beginning

**Comment by junranhe** [comment] 2015-09-22 05:26
I update and run it 30 minute  it not shutdown but hang up, cpu rate is 0%
INFO:root:Start training with 1 devices
Start training with 1 devices
INFO:root:Iteration[0] Train-accuracy=0.523378
Iteration[0] Train-accuracy=0.523378
INFO:root:Iteration[0] Time cost=140.093
Iteration[0] Time cost=140.093
INFO:root:Iteration[0] Validation-accuracy=0.648240
Iteration[0] Validation-accuracy=0.648240
INFO:root:Iteration[1] Train-accuracy=0.687980
Iteration[1] Train-accuracy=0.687980
INFO:root:Iteration[1] Time cost=141.330
Iteration[1] Time cost=141.330
INFO:root:Iteration[1] Validation-accuracy=0.727764
Iteration[1] Validation-accuracy=0.727764
INFO:root:Iteration[2] Train-accuracy=0.754728
Iteration[2] Train-accuracy=0.754728
INFO:root:Iteration[2] Time cost=140.836
Iteration[2] Time cost=140.836
INFO:root:Iteration[2] Validation-accuracy=0.773438
Iteration[2] Validation-accuracy=0.773438

**Comment by tqchen** [comment] 2015-09-22 05:40
I see, can you do ctrl+c and see where the trace come from?

**Comment by antinucleon** [comment] 2015-09-22 05:53
I tried 5 times but no luck to repeat. Did you update all dmlc-core and mshadow?

**Comment by antinucleon** [comment] 2015-09-22 06:14
Finally I repeat once. Thanks for letting us know

**Comment by junranhe** [comment] 2015-09-22 06:42
there is no trace when I ctrl+c, now I try it again

**Comment by junranhe** [comment] 2015-09-22 07:22
I update dmlc-core and mshadow every time....

**Comment by tqchen** [comment] 2015-09-22 21:55
The problem was caused by error handling at program exit @junranhe  I pushed some fix to the current mast at #131 Can you pull and try again if it works for you?

**Comment by junranhe** [comment] 2015-09-23 02:17
ok now :)

**Comment by tqchen** [comment] 2015-09-23 02:17
Thanks!

**Closed by tqchen** 2015-09-23 02:17 UTC

**Comment by junranhe** [comment] 2015-09-23 02:36
now I run it with 2 gpu, and get message,what matter?
kernel:BUG: soft lockup - CPU#0 stuck for 23s! [ksoftirqd/0:3]

**Comment by tqchen** [comment] 2015-09-23 02:59
We have not seen this before, will your program able to proceed? Seems have something to do with the overclocking.

**Comment by junranhe** [comment] 2015-09-23 03:09
my program is able to proceed, and cpu rate is only 100%, and no iteration result,   when I run it with 1 gnu, cpu rate is about 170%, I have the other job to do,so I will test it again later...

**Comment by mli** [comment] 2015-09-23 03:11
have you overlocked your cpu? or you may check the temperature by `sensors`

**Comment by junranhe** [comment] 2015-09-23 03:56
I don't know where the cpu is overlocked... the temperatures are not over 50 C, and I run purine and cxxnet 3 gpu are no problem...

**Comment by tqchen** [comment] 2015-09-23 04:26
Could due to we use cpu too optimistically. I pushed a fix to the master to make thread allocation more conservative, maybe if you can try again to see if the problem occurs. How many cores do you have in your machine?

**Comment by junranhe** [comment] 2015-09-23 06:39
6 core

**Comment by junranhe** [comment] 2015-09-23 08:18
I update and try it again, never get bug message, but it just hang up on the first round, first train_data iertation, it seems hang up on load data

**Comment by tqchen** [comment] 2015-09-24 01:31
Pushed another fix, @junranhe  Thanks for being so patient with the new stuff. Can you try again?

**Comment by junranhe** [comment] 2015-09-24 02:19
I think is some error in my machine, when I remove the error gnu 0(but I never run on it), and restart machine, the bug is gone:)

**Comment by mli** [comment] 2015-09-24 03:03
in that case, you can look at the error in dmesg. if that gpu is broken, it
should have been reported some errors there (i experienced that before.. in
my case, even nvidia-smi was hanged )

**Comment by junranhe** [comment] 2015-09-24 05:11
thanks~
